### ISSUE TITLE
Add a chrome extension docset

### ISSUE THREAD

**Issue by rainchen** [Kapeli/Dash-User-Contributions#101]
API Reference can be found here:
https://developer.chrome.com/extensions
API index:
https://developer.chrome.com/extensions/api_index

or the one by Opera
https://github.com/operasoftware/extension-docs

**Comment by gebrkn** [comment]
This has been added: https://github.com/Kapeli/Dash-User-Contributions/pull/283

**Comment by greatghoul** [comment]
Thank you for your nice work!

**Comment by gilmoreorless** [comment]
Nicely done, thanks @gebrkn

**Comment by rainchen** [comment]
excellent work! @gebrkn
