### ISSUE TITLE
[Question] Contributing docsets for individual boost libraries

### ISSUE THREAD

**Issue by ldionne** [Kapeli/Dash-User-Contributions#1012]
I tend to find that the docsets for the Boost libraries are not very useful,  since searching in them is difficult (perhaps I don't know how?). It seems like only full text search is available.

As the author of the Boost.Hana library, I would like Hana's docset to be better than that. Hence, I added support for generating docsets from Doxygen in Hana's build system (basically just run `make docset`).

I am wondering what is the best way to make this docset widely available. Ideally, if it could be provided as a "sub-docset" of `boost`, it would be great. Otherwise, it can also be provided as a user-contributed docset, but I fear that I would only reach a few users. Indeed, most people won't bother checking if a user-contributed docset exists for Hana, and they would just settle for the mediocre docset provided with the rest of Boost.

Summary: I'd like to provide a good docset for Boost.Hana and the setup to generate the docset is already there. What are my options?

Thanks for the awesome product.

**Comment by Kapeli** [comment]
Your only option is to contribute the docset here. I don't support any other way for users to contribute docsets.

The current Boost docset only indexes the library names, but nothing inside them. This is because the Boost libraries are documented using different formats.
