### ISSUE TITLE
Docset submission best practices

### ISSUE THREAD

**Issue by ViViDboarder** [Kapeli/Dash-User-Contributions#1015]
I'm about ready to submit a docset for Salesforce development, but I wanted to ask advice about packaging. Salesforce has two types of languages. One is the Apex coding language for controllers. The other is Visualforce for the front-end markup.

Should these be submitted as "Salesforce Apex" and "Salesforce Visualforce" or "Salesforce" with both bundled inside?

**Comment by Kapeli** [comment]
That's up to you. Are the docs separate for the 2 languages? If yes, I'd say separate the docsets too.

**Comment by ViViDboarder** [comment]
Sounds reasonable. Thanks.
