### ISSUE TITLE
Request: RxJS

### ISSUE THREAD

**Issue by jiayihu** [Kapeli/Dash-User-Contributions#1021]
I know [Angular 2](https://angular.io/docs/ts/latest/api/) is still in RC but a lot of people is starting using it, along with [RxJS v5-beta](http://reactivex.io/rxjs/) so I believe it would be very nice to add them to the available docs.

**Comment by Kapeli** [comment]
The Angular docset will be updated to v2 as soon as it becomes stable.

**Comment by squiddle** [comment]
just for reference there is an attempt by @riiid

https://github.com/riiid/rxjs-dash

**Comment by royling** [comment]
I am doing the same 😋 
https://github.com/royling/rxjs.docset

**Comment by Treri** [comment]
request for RxJS docset +1

**Comment by iansinnott** [comment]
I also decided to make a docset and was almost done before finding this issue 😄. It's been working well for me so far. The online docs for RxJS especially aren't the most easy to navigate so it's been great having it within Dash. If anyone wants to use it you can check it out here: https://github.com/iansinnott/rxjs-dash-docset

**Comment by Kapeli** [comment]
Closed by https://github.com/Kapeli/Dash-User-Contributions/pull/1472.
