### ISSUE TITLE
Update chrome extension docset

### ISSUE THREAD

**Issue by glukki** [Kapeli/Dash-User-Contributions#1032]
Could you, please?

Current docset covers Chrome v37.
The latest documentations seems to cover Chrome v46 or even later.

**Comment by Kapeli** [comment]
@gebrkn Can you look into this when you get a chance please?

**Comment by gebrkn** [comment]
Sorry for the delay guys, here's the PR https://github.com/Kapeli/Dash-User-Contributions/pull/1044
