### ISSUE TITLE
Yii 1 Docset

### ISSUE THREAD

**Issue by i7Grendel** [Kapeli/Dash-User-Contributions#1052]
Yii is a PHP framework which has existed for quite some time. There are two major versions: Yii 1 and Yii 2. Dash already comes with a Yii docset, but it's a docset for Yii 2. However, Yii 1 is still quite popular because Yii 1 and Yii 2 are very different so upgrading is a big undertaking.

I've built a Yii 1 docset for my own usage but I think that the many developers who are still using Yii 1 would find it useful as well. But strictly speaking, it doesn't meet the official requirements (although there are other docsets which seem to be exempt from this rule as well).

Would my docset be accepted? If so, I'll iron out the last issues and will submit it soon.

**Comment by Kapeli** [comment]
Yii 1 is also available in Dash:

![screen shot 2016-08-26 at 13 05 12](https://cloud.githubusercontent.com/assets/1445635/18001905/c37a2994-6b8d-11e6-8cbe-61ec8815d255.png)

**Comment by i7Grendel** [comment]
Thank you, I didn't know you could select the version. Then again, I'm using Zeal instead of Dash, which doesn't seem to support version selection.
