### ISSUE TITLE
How to update docsets shared via this repo?

### ISSUE THREAD

**Issue by deanishe** [Kapeli/Dash-User-Contributions#1079]
I have a [docset for my Alfred-Workflow library](https://github.com/deanishe/alfred-workflow/tree/master/docs/Alfred-Workflow.docset), which I'd like to make "officially" available to other AW+Dash users, but I'm not sure as to how I should best go about that ("best" meaning "easiest for me, as long as it's not a PITA for users").

Adding docsets to this repo is "highly recommended" over providing a feed, but how do I update them? Do I have to submit a new pull request every time? Is there a script to automate the process?

Forking and updating the repo, then submitting a pull request appears to be a lot more complicated (and more importantly, *significantly* harder to automate, than providing a feed).

At first blush, it seems to me that it would be a whole lot easier for me to dump the docset and a feed in the `gh-pages` branch on GitHub and put a `dash-feed://` URL in the README rather than bugger about with cloning repos and submitting pull requests.

Am I missing something here?

**Comment by Kapeli** [comment]
You're not missing anything. You have to make a pull request whenever you want to update the docset.

A feed is easier, yes.

**Comment by deanishe** [comment]
Right you are. Thanks for the speedy response, and more importantly the awesome app. 

Out of interest, how often does Dash check feeds for updates?

**Comment by Kapeli** [comment]
> Out of interest, how often does Dash check feeds for updates?

At each launch and every 24 hours.

**Comment by deanishe** [comment]
Bloody hell, you're quick!

Thanks again!
