### ISSUE TITLE
Request: Go Local Docs

### ISSUE THREAD

**Issue by dav-** [Kapeli/Dash-User-Contributions#1125]
In this issue I'm requesting support for viewing local Golang documentation within Dash, akin to how the `godoc -http` tool works. This isn't directly related to this repo, but since there is no general Dash issue tracker I can find, it seems like the most appropriate place.

---

#### Reasoning
A large portion of the documentation I reference on a daily basis is part of private projects with only local documentation. I do reference the public standard/third-party library docs, but my private documentation is what's most important to me because it's ever-changing.

I am considering writing a script to generate Dash Docsets from my local documentation, but as I've read in [this issue](https://github.com/golang/gddo/issues/149) this seems to be something that other users have requested as well, so I figured I would first request this feature in hopes that it could be implemented natively. If Dash or its relevant components were open source (*hint hint*) I could do it myself and submit a PR, but alas it isn't so I'll have to just beg for the feature instead. 

I really think Go developers would benefit from this feature, and I don't think it should be difficult to implement, especially since you presumably already have a parser for the online Godoc pages. 

#### User Friendliness
The [major concern you cited](https://github.com/golang/gddo/issues/149#issuecomment-36059937) in that issue I mentioned was user friendliness. I don't believe this would be an issue because with a standard Go environment setup  all packages will be under `$GOPATH/src`. This should apply to 99% of Go devs since it is recommended by the Go documentation and Go is a very minimalism-centric language with strict conventions. From the [Golang.org Workspaces documentation](https://golang.org/doc/code.html#Workspaces):

> Most Go programmers keep all their Go source code and dependencies in a single workspace.

The bottom line is that if it doesn't work for a user, it's because their environment is configured in a non-standard way, OR possibly that they're developing on a remote server over SSH or something. Either way, I would guess that these users should be in the vast minority.

#### Implementation
If you examine the [godoc command documentation](https://godoc.org/golang.org/x/tools/cmd/godoc) and mess around with the `godoc` tool, you should be able to see how easy it would be to extract local documentation. 

1. Try running `godoc $GOPATH/src`. This will give you a list of all local top-level directories. (If you have none, just `go get github.com/gorilla/mux` to test it out).
2. Next, pick one of these directories and run `godoc $GOPATH/src/<subdirectory>`. There will probably be more subdirectories. 
3. Repeat and you should finally be at the package level (which may even contain additional subdirectories, and so on).
4. Once you reach a package, try running `godoc -html $GOPATH/src/directory/subdirectory/package` , e.g. `godoc -html $GOPATH/src/github.com/gorilla/mux`
5. Viola, the HTML source for the documentation of that package should be printed to STDOUT. Now just run that HTML through whatever parser you've already got built for generating Go Docsets. 

It would be nice if there was a pane similar to the existing `Dash > Preferences > Third Party Sources > Go Docsets` for local Go packages, or if this feature was integrated into the existing pane. Typing in the search bar would search the local `$GOPATH/src` directories (either using `godoc` or custom filesystem traversal). Dash would then display any matching packages as results which could be installed as Docsets.

Ideally, there would be some mechanism to update these local Docsets automatically upon changes to the source code, as any in-development packages will change frequently. 

#### Conclusion
To close, I just want to emphasize how much Go developers LOVE documentation. Anyone using [GoLint](https://github.com/golang/lint) and/or adhering to the official [Effective Go](https://golang.org/doc/effective_go.html#commentary) style should be documenting ALL of their exported types, fields, methods, functions, etc.

We all currently have to rely on the nice but somewhat lacking Godoc documentation, but it's not very pretty, it doesn't integrate with other documentation (like JS/HTML/SQL/etc, which we often use simultaneously), etc. Dash is much nicer, and I think you have a large potential market of developers who would love to purchase your product if was fully integrated with our workflows.

**Comment by Kapeli** [comment]
Thanks for the very detailed request. Dash does not have a public issue tracker, so please [contact me](https://kapeli.com/contact) in the future with your requests.

This is something that I plan on doing, but it's quite low priority as I haven't seen much demand for it. You're the 2nd or 3rd user to mention it so far.

If you'd like to implement something yourself, please email me and I'll be happy to explain how Dash generates the docsets based on godoc and also provide the source code.

**Comment by jiaqingw** [comment]
I found myself in the same boat as the dav was.

**Comment by tmaiaroto** [comment]
I'm constantly keeping open browser tabs for documentation now when working with Go. It's defeating the purpose of Dash and I reach for Dash less and less the more familiar I become with Go's standard library. I suspect this is similar for many languages...The problem is that most don't have a great built-in documentation facility whereas Go does.

If there's even some command line process I could run to generate the docsets for Dashlane, I wouldn't mind periodically running that as I pulled down new packages.

**Comment by Kapeli** [comment]
I completely agree I should add what @dav- described, but unfortunately I have to prioritise other things that would benefit a larger number of users.

> If there's even some command line process I could run to generate the docsets for Dashlane, I wouldn't mind periodically running that as I pulled down new packages.

What I told @dav- still stands:

If you'd like to implement something yourself, please email me and I'll be happy to explain how Dash generates the docsets based on godoc (Preferences > Downloads > Go Docsets) and also provide the source code.

**Comment by ericychoi** [comment]
+1 here this is keeping me from purchasing the full version atm..

**Comment by joshualawson** [comment]
+1 for this, would be amazing and also open up dash to go devs!

**Comment by wuudjac** [comment]
Hi, I've written a command line tool called `godocdash` to do it.

> https://github.com/wuudjac/godocdash

Typically, just `go get` this command and run, it takes only a few seconds to generate the docset.

I've tested the docset generated in Zeal, but I don't have any Mac device now, maybe someone could help me test how the docset looks in Dash?

**Comment by PeterFaiman** [comment]
@wuudjac it looks fine in Dash, only complaint so far is the sidebar shows really long names, e.g. `github.com/prometheus/client_model/go.Gauge`. My sidebar is about 200px wide, so it shows `github.com/prome`, which is obviously close to useless. I currently depend on few enough Go packages that I'd rather manually install them all for the shorter names. But I would LOVE to use this tool, or even just a tool that ordered Dash to install the docsets that are present in my GOPATH.
