### ISSUE TITLE
FFmpeg Docset: Guides gone

### ISSUE THREAD

**Issue by klausbadelt** [Kapeli/Dash-User-Contributions#1140]
Guides are gone after #1132. This makes it "almost useless", to quote #1118 ;-).

_Little side note - I wonder if maybe a PR to my  [original docset generator](https://github.com/klausbadelt/ffmpeg-docset) would have been more productive/collaborative than a competing project..?_

**Comment by Kapeli** [comment]
Would you like me to revert the docset to your version? Or would you like to make a pull request that also updates the docset?

// cc @steve3d

**Comment by steve3d** [comment]
OK，l have found the problem, I'll update the docsets later today.

**Comment by klausbadelt** [comment]
@Kapeli I apprectiate @steve3d 's contribution but his generator is new from scratch, so I can't really submit a PR now. (My understanding of the Github collaborative coding spirit is somehow different.. ) But practically speaking, let's keep going with this new one as it includes a missing feature of the other one. Once @steve3d fixes his we should be better off for Dash, and that's all we want :-) Thanks for asking!

**Comment by Kapeli** [comment]
Does https://github.com/Kapeli/Dash-User-Contributions/pull/1142 fix this?

**Comment by klausbadelt** [comment]
Yes but introduced other issues (which I had solved already... ;-) ).

**Comment by Kapeli** [comment]
Should I revert the docset to your version?

**Comment by klausbadelt** [comment]
I think he is closer to a complete set now, thank you.

**Comment by Kapeli** [comment]
Ok. Closing this issue.
