### ISSUE TITLE
Angular 1.X.X?

### ISSUE THREAD

**Issue by psrivongse** [Kapeli/Dash-User-Contributions#1144]
I can no longer access angular 1.x docs because they are now 2.x.

I am using Zeal on Windows, from my understanding, utilizes Dash Docsets. 
Hoping there will be two versions of documentation for Angular!

Thank you!

**Comment by Kapeli** [comment]
Dash users can install Angular 1.x from Preferences. Downloads. As far as I know Zeal doesn't support versioned docsets yet. There's a GitHub issue about it in Zeal's repo, but I can't find it.

![screen shot 2016-10-21 at 11 59 52](https://cloud.githubusercontent.com/assets/1445635/19592768/e3f1d63a-9785-11e6-9572-446bcfc1a0a3.png)
