### ISSUE TITLE
pd.read_html() not working showing error in _html5lib.py

### ISSUE THREAD

**Issue by prakritidev** [Kapeli/Dash-User-Contributions#1147]
pd.read_html() not working showing error in _html5lib.py,line 70 class TreeBuilderForHtml5lib
**CODE**
import pandas as pd 
import html5lib
import lxml
data  = pd.read_html('https://blockchain.info/blocks')

**OUTPUT:**
after updating beautifulsoup this is the output

File "C:\Anaconda2\lib\site-packages\bs4\builder\_html5lib.py", line 70, in <module>
class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by Kapeli** [comment]
This is not the right repo.
