### ISSUE TITLE
User contribution "SDL" name

### ISSUE THREAD

**Issue by JamaicanRumCream** [Kapeli/Dash-User-Contributions#1191]
Using acronyms for doc sets should be spelled out or have the full name in parenthesis. I work with an "SDL" framework which is "Smart Device Link" which is for automobile-phone connections. The Dash SDL is "simple direct media layer". Without more context, any acronym name can easily be misunderstood.

**Comment by Kapeli** [comment]
Thanks for the feedback. I won't allow acronyms in the future.
