### ISSUE TITLE
Docset for Fat-Free Framework (php, mvc)

### ISSUE THREAD

**Issue by pixeline** [Kapeli/Dash-User-Contributions#1218]
Hello,

I have tried to create a docset for the fat-free framework using Doxygen. It seemed to go fine, but when I used it inside Dash, it says the docset is empty. I've published an open repository so you can have a look and tell me what I'm doing wrong.

https://github.com/pixeline/Fat-free-Framework-Docset-generation-for-Dash

Here is what I did:
- installed Doxygen Mac Os X GUI
- let it parse local folder containing the source. It generated the html and latex folders that you can find in this repo.
- then I followed steps 12.1 to 12.5
- adapted the generate.php script and ran `php generate.php`

To reproduce the issue, simply cd into the folder, then run `php generate.php`. 
The script wants to generate files: 
"appendixes.assertions", "appendixes.annotations", "incomplete-and-skipped-tests", "test-doubles", "writing-tests-for-fat-free-framework" 

but does not find them, I guess. Are they needed ?  I adapted this script from the PHPUnit generation script so I'm not sure they are required by Dash.
Thank you,
a.

**Comment by Kapeli** [comment]
See https://kapeli.com/docsets#doxygen for instructions on how to use Doxygen to generate docsets

**Comment by pixeline** [comment]
Thanks @Kapeli . I did, but the generated makefile is looking for a nonexistent docsetutil. It seems one needs xcode. Also saw a tweet from you (2013) that states docsetutil is not necessary. I guess I've lost my way inside the documentation :) Will try another time.

**Comment by Kapeli** [comment]
docsetutil is needed for Doxygen-generated docsets, as it produces docsets that are compatible with Xcode.

It's not needed for Dash-only docsets - https://kapeli.com/docsets#dashDocset.
