### ISSUE TITLE
Request: pyqtgraph

### ISSUE THREAD

**Issue by jannismain** [Kapeli/Dash-User-Contributions#1236]
URL: http://www.pyqtgraph.org/documentation/

This is generated by sphinx, so the docset creation should be pretty straight-forward. I will look into this, when I have time to read through the docset generation guidelines :-)

**Comment by j9ac9k** [comment]
Currently working on this! I have a PR that uploads a docset as an artifact on the pyqtgraph CI, but presently working on automated submissino to docs here on release.
