### ISSUE TITLE
Latest update of terraform docset has broken static assets

### ISSUE THREAD

**Issue by glenjamin** [Kapeli/Dash-User-Contributions#1308]
See screenshot for what it looks like

<img width="1436" alt="screen shot 2017-03-14 at 13 17 56" src="https://cloud.githubusercontent.com/assets/151272/23902325/a74bddb2-08b8-11e7-99d9-4b62ade4644d.png">

**Comment by Kapeli** [comment]
@f440 Can you look into this please?

**Comment by f440** [comment]
Sorry, It's my mistake. Please wait for merging with #1309.
