### ISSUE TITLE
Update Tensorflow docset

### ISSUE THREAD

**Issue by slcott** [Kapeli/Dash-User-Contributions#1326]
https://github.com/ppwwyyxx/dash-docset-tensorflow

is newer than 

https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/TensorFlow

**Comment by Kapeli** [comment]
@ppwwyyxx Can you update when you get a chance?

**Comment by ppwwyyxx** [comment]
Of course! Will update soon.
