### ISSUE TITLE
wxWidgets docset displays user's full path in #include hints

### ISSUE THREAD

**Issue by mesalu** [Kapeli/Dash-User-Contributions#1376]
Here is an example:
![screen shot 2017-04-21 at 5 51 04 pm](https://cloud.githubusercontent.com/assets/6109654/25299999/213ea4c2-26bb-11e7-99f6-d865aada009f.png)

Note the `#include` section:
`#include </Users/Rand0m/Desktop/Temp/wxWidgets-3.1.0/interface/wx/gbsizer.h>`

wx's documentation is generated by doxygen, and if I remember correctly setting doxygen's STRIP_FROM_INC_PATH to the appropriate value will correct this.

**Comment by mesalu** [comment]
Looking at wx's current doxygen config file:
https://github.com/wxWidgets/wxWidgets/blob/master/docs/doxygen/Doxyfile

This has already been accounted for. 
A fresh doxygen build will solve this.

**Comment by Kapeli** [comment]
@davidwed Can you take a look at this please?
