### ISSUE TITLE
Keras not maintained?

### ISSUE THREAD

**Issue by kkweon** [Kapeli/Dash-User-Contributions#1381]
I was about to send a PR but I've found out the Keras docset is already in the repo.
But, it seems it's not updated to the latest considering the latest version of keras is 2.0+

So the question is 
* Can I overwrite it? If not, please let me know what I can do.
* my github link for Keras docset: https://github.com/kkweon/keras-docset

**Comment by Kapeli** [comment]
You can take over and maintain it yourself if you want.

// cc @iamaziz
