### ISSUE TITLE
Haskell docset remove GL functions

### ISSUE THREAD

**Issue by Yanpas** [Kapeli/Dash-User-Contributions#1393]
The vast majority of functions in hakell docset relate to GL, (Graphics.GL module). How about removing all of them or most of them? The spoil search results, mostly consist of C macros and IMHO very rarely used. It would be much easier to read OpenGL documentation instead of haskell's own

**Comment by Kapeli** [comment]
Good idea. I'll do that.

Please note that this repo is for user contributed docsets (Haskell is not user contributed). In the future please [contact me](https://kapeli.com/contact) with issues regarding the main docsets.
