### ISSUE TITLE
Should have a repository with doc compilation scripts

### ISSUE THREAD

**Issue by jnothman** [Kapeli/Dash-User-Contributions#1433]
Asking each docset to be contributed independently has the benefit of quality assurance, but is a waste of energy when docs get updated.

A more maintainable model would include:
* a docset compilation script for each project, which fetches the code required for documentation and builds it to a specified location
* perhaps a version check script for each project to determine if the documentation is out of date

Not only would this help with the maintenance of existing packages, but the existence of previous compilation scripts will help maintainers of packages create docsets from diverse sources.

**Comment by Kapeli** [comment]
Docs often change, so I've found that an automated update process doesn't work, as these doc changes would not be noticed and the quality of the docset decreases over time.

Most docset authors include a link to the repository containing the generation script in the README.

**Comment by jnothman** [comment]
And what's the harm of automatically updating, with or without human
intervention, if the docs change frequently? The main issue I see is
managing dependencies for build scripts

**Comment by Kapeli** [comment]
I think there's a misunderstanding. By "docs often change" I mean the doc format itself changes and the script becomes outdated. For example if the CSS class that defines a function is changed from "func" to "function", a script that relies on that will stop indexing functions.

Human verification is required, so there's not much benefit in automating the process.

**Comment by jnothman** [comment]
right :/ That's a bit disappointing. thanks for your attention
