### ISSUE TITLE
Request: Terraform

### ISSUE THREAD

**Issue by OliverCole** [Kapeli/Dash-User-Contributions#1448]
[Terraform](https://www.terraform.io) is an infrastructure-as-code tool that works on many different cloud providers. It has copious [docs](https://www.terraform.io/docs/providers/index.html).

I believe they are planning a structural change in the docs however: https://github.com/hashicorp/terraform/issues/14266#issuecomment-300221900, so it might be worth waiting a little while.

**Comment by davewongillies** [comment]
The Terraform docset is already been contributed to this repo by @f440: https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Terraform
