### ISSUE TITLE
I hope we can have  a sklearn docset.

### ISSUE THREAD

**Issue by michael-ji0406** [Kapeli/Dash-User-Contributions#1457]
The website is http://scikit-learn.org/. I really need a docset of sklearn. Thx

**Comment by Kapeli** [comment]
A user-contributed scikit-learn docset is already available.

**Comment by SnakeHit** [comment]
> A user-contributed scikit-learn docset is already available.

three years... How's it going

**Comment by dukai1011** [comment]
5 years ago, still haven't added.
