### ISSUE TITLE
Cannot download bloomberg/bde

### ISSUE THREAD

**Issue by ElvisXuHuang** [Kapeli/Dash-User-Contributions#1491]
I kept getting error "Error: Could not clone git repo. Output:". I can run git clone directly without an issue. The git repo is https://github.com/bloomberg/bde

Since BDE is the only thing used in Bloomberg and there are 4000 developers there, it might also be a good idea to add a docset

**Comment by Kapeli** [comment]
Please email me about this.

This repo is for Preferences > Downloads > User Contributed, not Preferences > Downloads > GitHub.
