### ISSUE TITLE
Flowtype: Upgrade to v0.51.1 Documentation

### ISSUE THREAD

**Issue by peterpme** [Kapeli/Dash-User-Contributions#1494]
Hey everyone,

Awesome awesome work! I'm looking for Opaque Type Aliases and unfortunately they're not in this docset. What can _I_ do to personally help get this updated, otherwise what can be done to upgrade?

Thanks!

**Comment by Kapeli** [comment]
@epitaphmike Can you update when you get a chance please?

@peterpme You can update the docset and submit a pull request yourself if you want. Start at https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Flow.

**Comment by Kapeli** [comment]
Closing in favor of https://github.com/Kapeli/Dash-User-Contributions/issues/1567
