### ISSUE TITLE
Request: DOM Docset

### ISSUE THREAD

**Issue by awareness481** [Kapeli/Dash-User-Contributions#1497]
The [MDN offline docs](https://developer.mozilla.org/en-US/docs/MDN/About) include a separate folder for DOM documentation. Also, the [offline docs](https://kapeli.com/mdn_offline) made by Kapeli include DOM documentation as well.

Presumably, given the easy access to DOM documentation files, it shouldn't be too hard for someone who has some experience with docsets regarding Dash to implement it. It would be a nice addition for web developers.

A similar implementation to the way [devdocs](http://devdocs.io/) would be great. If nobody is interested in implementing it, I can try doing it and contributing it to the project but I'm not familiar with SQL just yet.

**Comment by Kapeli** [comment]
DOM docs are part of the JavaScript docset.
