### ISSUE TITLE
uikit version 3

### ISSUE THREAD

**Issue by ckidow** [Kapeli/Dash-User-Contributions#1530]
Hi there!

Is it possible to update the uikit docset to uikit version 3? Would be awesome!

Thx in advance

**Comment by devtype** [comment]
Hi,
I agree this would be very helpful

**Comment by Kapeli** [comment]
@coxy or @schinckel Can you update when you get a chance?

**Comment by schinckel** [comment]
@Kapeli Do I need to do anything to allow pinning to the previous version (because I'm not updating my installation of UIkit anytime soon... ;)

**Comment by schinckel** [comment]
Or should I have a seperate UIkit3 docset?

**Comment by schinckel** [comment]
Okay, think I have figured out the versions stuff. Do I need my old file to move to `versions/x.y.z/UIkit.tgz`, or can I leave it as the original location?

**Comment by coxy** [comment]
@schinckel thanks - happy for you to take over any future updates too as I don't have a lot of free time lately
