### ISSUE TITLE
Request: Upgrade Scikit-learn documentation to v0.19 

### ISSUE THREAD

**Issue by Tafkas** [Kapeli/Dash-User-Contributions#1534]
Current version is [0.19](http://scikit-learn.org/0.19/documentation.html). It would be nice to have it as a package for Dash.

@jaypeedevlin

**Comment by jaypeedevlin** [comment]
@Tafkas the instructions for updating it yourself [are here](https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Scikit), it's very straightforward!

**Comment by jaypeedevlin** [comment]
Nice work!!
