### ISSUE TITLE
Redux Docset maintainer needed

### ISSUE THREAD

**Issue by epitaphmike** [Kapeli/Dash-User-Contributions#1566]
I can no longer have time to maintain this docset and I am looking for additional contributors to assist. My repo is located at [https://github.com/epitaphmike/redux-dash](https://github.com/epitaphmike/redux-dash). If this is something you are interested in helping with please reach out. Thank you.

**Comment by grawlinson** [comment]
This really should be re-opened due to the docset being out of date, and the repository mentioned above has disappeared.

@epitaphmike, do you have a local copy, hopefully?
