### ISSUE TITLE
Jest Docset maintainer needed

### ISSUE THREAD

**Issue by epitaphmike** [Kapeli/Dash-User-Contributions#1569]
I can no longer have time to maintain this docset and I am looking for additional contributors to assist. My repo is located at https://github.com/epitaphmike/jest-dash. If this is something you are interested in helping with please reach out. Thank you.

**Comment by chinesedfan** [comment]
@epitaphmike I will take it. 😄

**Comment by epitaphmike** [comment]
@chinesedfan Join the group https://github.com/dash-docs-community to start maintaining the jest-dash docset. Then merge the set to this repo.

**Comment by dsummersl** [comment]
Does this project still need a maintainer? I notice its about 5 major versions out of date...

**Comment by epitaphmike** [comment]
Very much so. You can join the group here
https://github.com/dash-docs-community/jest-dash to start maintaining, then
merge to https://github.com/Kapeli/Dash-User-Contributions

Thank you for your help.

**Comment by chinesedfan** [comment]
@epitaphmike Did you see my apply about 1.5 year ago? In fact, you can invite me directly. :P
