### ISSUE TITLE
index.html not working in Google Apps Script docset

### ISSUE THREAD

**Issue by almai** [Kapeli/Dash-User-Contributions#1579]
I've added the Google Apps Script docset yesterday to the repository. When I generate it and and include it locally the index.html page gets displayed. But when I call the docset from within Dash there's no index page at all. Please let me know what to do, to fix that problem.

**Comment by Kapeli** [comment]
Change the path in Info.plist from `./gas/index.html` to `gas/index.html` and it should work. Submit a pull request with the updated docset.
