### ISSUE TITLE
AngularDart docset stopped updating

### ISSUE THREAD

**Issue by filiph** [Kapeli/Dash-User-Contributions#1637]
AngularDart is now on version 4, Dash only has version 2.0.

The api reference is here: https://webdev.dartlang.org/api (same format as AngularJS)
API docs (probably what you want) is here: https://www.dartdocs.org/documentation/angular/4.0.0/angular/angular-library.html

Also, a cheat sheet is here: https://webdev.dartlang.org/angular/cheatsheet

**Comment by Kapeli** [comment]
I've decided to discontinue the AngularDart docset for now. They've changed their documentation format 3 times I think and each time it was JavaScript-heavy (which is very hard to turn into a docset). The AngularDocset was used only by 0.1% of Dash users.

Feel free to open a new issue requesting a user-contributed AngularDart docset.
