### ISSUE TITLE
Request: Solidity docs

### ISSUE THREAD

**Issue by jesseditson** [Kapeli/Dash-User-Contributions#1685]
http://solidity.readthedocs.io/

**Comment by joeblau** [comment]
I just came here to request this as well.  I was just on a 5 hour flight with no internet and this would have been handy.

**Comment by oschvr** [comment]
I've made a repository to aggregate the docset to Dash. Just sent a pull request in order to add them.

Feel free to [check it out](https://github.com/oschvr/solidity-dash)

**Comment by jesseditson** [comment]
You're a hero! Here's how to install:

![image](https://user-images.githubusercontent.com/370239/40381998-15fa611c-5db2-11e8-8ae7-213768395e18.png)
