### ISSUE TITLE
Electron 1.7.9 docset have a lot of blank at top

### ISSUE THREAD

**Issue by daviyang35** [Kapeli/Dash-User-Contributions#1692]
Such as the title

Dash 4.1.2(460)
Electron v1.7.9 docset from User Contributed

```
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.2 (17C88)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98) 
```

**Comment by Kapeli** [comment]
// cc @pirafrank @wearhere

**Comment by pirafrank** [comment]
I’m aware of the issue. Electron completely changed the way their doc website works. I’ve already drafted a fix on my github and I need some time to further test. I should make it for this holiday season. 

Cheers

Francesco

**Comment by daviyang35** [comment]
@pirafrank Thanks a lot.

**Comment by Anrock** [comment]
@pirafrank any updates? Also, are you going to upload docs for 1.8.x?

**Comment by pirafrank** [comment]
Hi, docs were packed for 1.8.x.
I have to check them then I’ll submit PR.
I’ll notify to you here too if you want to.

Also fix for this bug was deployed to my github repo weeks ago. It works for all but the homepage (displays in non US lang).

Francesco

**Comment by Anrock** [comment]
@pirafrank thank you for your work. No need to notify about PR here - i'll just wait until Dash updates it.

**Comment by daviyang35** [comment]
@pirafrank Thans for your job.

**Comment by pirafrank** [comment]
Little update on this.
I need some time to nail a fix for v1.8.x as starting with this version they seem to have broken my sqlite indexing. Need to rebuild.
v1.7.9 (repack) and 1.7.11 work fine btw.
I'll do just one PR as soon as I fix.

**Comment by bwiggs** [comment]
Looking forward to it @pirafrank !

**Comment by pirafrank** [comment]
I think this issue can be closed as I fixed it in [PR 1816](https://github.com/Kapeli/Dash-User-Contributions/pull/1816)
