### ISSUE TITLE
XUL docset has a spanish page among English

### ISSUE THREAD

**Issue by wolfbeast** [Kapeli/Dash-User-Contributions#1714]
The XUL docset available within Zeal has a Spanish-language page in among the otherwise English references. I hope this is the correct location to report this.
The Spanish page is the "content" element reference linked from the index page in the docset.

**Comment by Kapeli** [comment]
The XUL docset has been discontinued a while ago (almost no Dash user was using it). @trollixx you should consider removing XUL from Zeal.

**Comment by wolfbeast** [comment]
Um, no please don't remove it from Zeal. Mozilla has made the XUL reference pretty much undiscoverable at this point and will probably remove it from MDN; XUL however is alive and well and having a language reference in Zeal is going to be indispensable when the on-line references are removed.

**Comment by trollixx** [comment]
Too late, sorry :)

If it's really needed, then consider contributing it to this repo. Then you'd be able to install it in Zeal via http://zealusercontributions.herokuapp.com and eventually directly from Zeal (when zealdocs/zeal#170 is implemented).

**Comment by wolfbeast** [comment]
How am I going to contribute it to this repo if you've yanked it out from under me? XD

**Comment by trollixx** [comment]
It was never in this repo, but in [Kapeli/feeds](https://github.com/Kapeli/feeds).
