### ISSUE TITLE
Update Android Gradle Plugin docset to 3.0.0

### ISSUE THREAD

**Issue by ubuntudroid** [Kapeli/Dash-User-Contributions#1736]
Hey, would be great if the Android Gradle Plugin could be updated to version 3.0.0, currently it's on 2.2.0.

https://google.github.io/android-gradle-dsl/current/index.html

**Comment by Kapeli** [comment]
// cc @faithfracture & @tokou

**Comment by tokou** [comment]
#1738

**Comment by ubuntudroid** [comment]
Wow, that was really fast! Thanks a lot! 😍
