### ISSUE TITLE
Request: Ability to strip string from @clipboard variable in snippets

### ISSUE THREAD

**Issue by Orrison** [Kapeli/Dash-User-Contributions#1740]
It would be awesome if something could be done with defining certain strings that should be stripped from the @clipboard variable.

Use case example: 

- I want to make a snippet to quickly look up the URL in my clipboard on dnsspy.io
- Their link format to look up a site is: https://dnsspy.io/scan/[URL OF SITE WITHOUT PROTOCOL]
- Because DNSSpy requires the URL submitted to NOT contain protocol (HTTP/HTTPS) it would be awesome if I could set @clipboard to remove that during expansion
- Perhaps something like @clipboard-http://

Just thought a feature like that could be pretty useful.

**Comment by Kapeli** [comment]
This repo is for user contributed docsets. It's not for Dash feature requests. Please [contact me](https://kapeli.com/contact) with those.

**Comment by Orrison** [comment]
Great, sorry about that
