### ISSUE TITLE
Can not download Ant Design

### ISSUE THREAD

**Issue by yesmeck** [Kapeli/Dash-User-Contributions#1750]
After #1744 been merged, I can search Ant Design now

<img width="820" alt="screen shot 2018-02-10 at 01 33 06" src="https://user-images.githubusercontent.com/465125/36041060-5d46245c-0e02-11e8-81e0-7fc84a324013.png">

But I can not download it

<img width="820" alt="screen shot 2018-02-10 at 01 33 54" src="https://user-images.githubusercontent.com/465125/36041092-78d72446-0e02-11e8-942f-85dd4ce8323e.png">

I can download other docsets without error. @Kapeli could you check what is wrong?

**Comment by Kapeli** [comment]
Should be ok now.

**Comment by yesmeck** [comment]
Thanks
