### ISSUE TITLE
how to add for zeal

### ISSUE THREAD

**Issue by skgbanga** [Kapeli/Dash-User-Contributions#1825]
Is it possible to add these to zeal?

`Dash's Preferences > Downloads > User Contributed.` probably only works for Dash, and not zeal.

**Comment by Kapeli** [comment]
I have no idea what the current state of User Contributed docset support is in Zeal. Please ask this in Zeal's repo.

**Comment by skgbanga** [comment]
Fair enough. Thanks for the pointer.
