### ISSUE TITLE
How to maintain docset of two versions

### ISSUE THREAD

**Issue by laoreja** [Kapeli/Dash-User-Contributions#1861]
Hi, I would like to keep the docsets for both PyTorch 0.3.0 and 0.4.0, but I failed to trigger PyTorch 0.4.0 until I delete PyTorch 0.3.0's docset.

My PyTorch 0.3.0 comes from the user contribution.
I made 0.4.0 myself, with some basic effort to rename it (both in the filename and the plist).

I cannot put my 0.4.0 here, it's generated from this script: https://github.com/pytorch/pytorch/blob/v0.4.0/docs/Makefile

**Comment by Kapeli** [comment]
Docsets support specific versions:

![screen shot 2018-04-27 at 23 11 15](https://user-images.githubusercontent.com/1445635/39383019-5432e72e-4a70-11e8-997f-8dd2ee16dbd7.png)

**Comment by haroldofurtado** [comment]
I still don't know why don't have Ruby 2.5.8
