### ISSUE TITLE
how can I generate index file?

### ISSUE THREAD

**Issue by icq4ever** [Kapeli/Dash-User-Contributions#1880]
recently openFrameworks updated to 0.10.0 so I want to make docset for dash.
but I got stucked. 

first, docsetutil is missing on macos sierra. (it's not issue with dashdoc right?)

second, after `make` in `build/html` directory,  and trying to open docset file, dash saids
"The docset does not have a index file, maybe the docset has not been indexed?"

it's not happened I did before. something changed? or am I missing something?

plus. I tried with dashing.. but class name and search keyword is not well indexed... 

any help?

**Comment by icq4ever** [comment]
I tried with [doxytag2zealdb](https://github.com/vedvyas/doxytag2zealdb) but same error message.
opend with SQL DB viewer. seems that indxed. (screenshot below)

<img width="1256" alt="screen shot 2018-05-08 at 10 10 35 pm" src="https://user-images.githubusercontent.com/530796/39759090-aa177200-530c-11e8-8c0b-f739fe513348.png">
<img width="1256" alt="screen shot 2018-05-08 at 10 10 37 pm" src="https://user-images.githubusercontent.com/530796/39759091-ab8179d8-530c-11e8-8980-b3174626db27.png">

but I don't think it's well done.  I checked old version of docsets.. it's totally different.
(0.9.8 docset)

<img width="1256" alt="screen shot 2018-05-08 at 10 12 13 pm" src="https://user-images.githubusercontent.com/530796/39759176-ed7bc2d0-530c-11e8-9b51-a60ba6ecdfc2.png">
<img width="1256" alt="screen shot 2018-05-08 at 10 12 25 pm" src="https://user-images.githubusercontent.com/530796/39759178-eeaf3330-530c-11e8-9b7a-977e78853435.png">

**Comment by Kapeli** [comment]
There are 2 docset formats: Apple (which has been discontinued), and Dash.

You can get docsetutil by downloading an older version of Xcode. I think Xcode 8.3.3 has it (use https://xcodereleases.com).

As for your doxytag2zealdb attempt, I think what went wrong is that you don't have the `isDashDocset` key in your Info.plist. See https://kapeli.com/resources/Info.plist.

**Comment by icq4ever** [comment]
@Kapeli what a stupid mistake.. `isDashDocset` is missing. now it works. thanks a lot :+1:

**Comment by vedvyas** [comment]
The latest release of doxytag2zealdb (0.3.0) now updates Info.plist by default (unless users pass `--dont-update-info-plist`). Sorry about that :-)
