### ISSUE TITLE
update OpenCL docset to OpenCL 1.2 and 2.0

### ISSUE THREAD

**Issue by mikeseven** [Kapeli/Dash-User-Contributions#189]
OpenCL 1.2: https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/
OpenCL 2.0: https://www.khronos.org/registry/cl/sdk/2.0/docs/man/xhtml/

**Comment by emoon** [comment]
Will start work on this today.

**Comment by emoon** [comment]
Added PL here: https://github.com/Kapeli/Dash-User-Contributions/pull/272

**Comment by emoon** [comment]
@mikeseven The 1.2 and 2.0 versions are now live in Dash.

**Comment by emoon** [comment]
@Kapeli As @mikeseven hasn't replied to this for quite a while I think it's fine to close this one now.

**Comment by Kapeli** [comment]
Thank you! I should have closed this issue as soon as you added the docsets. I forgot.
