### ISSUE TITLE
Please update PIL for python

### ISSUE THREAD

**Issue by txytju** [Kapeli/Dash-User-Contributions#1892]
python PIL is now 5.1.X, please update for that, thanks!

**Comment by Kapeli** [comment]
@153957 Could you update when you get a chance?

**Comment by 153957** [comment]
Im on it!

Would it be useful to still add some in-between versions? e.g. 4.3.0, 3.4.0 (latest for each major version)

**Comment by Kapeli** [comment]
Thanks for the update! No idea if the other versions would be needed, it's up to you.

**Comment by txytju** [comment]
Thanks for that! @153957 @Kapeli
