### ISSUE TITLE
feed for zeal is needed

### ISSUE THREAD

**Issue by specter119** [Kapeli/Dash-User-Contributions#1904]
I have multiply devices including mac and Linux. and I have to use zeal on Linux instead of Dash.

The only way for zeal to get user contributed docsets automatically is  build a feed like [dash-contrib-docset-feeds](https://github.com/hashhar/dash-contrib-docset-feeds). But it will be more continent if there is an "official feed" for the ones who use windows and Linux. I don't know whether you mind, since it obviouly should be the work on the zeal side.

Thanks in any way.

**Comment by Kapeli** [comment]
Please contact Zeal's developer regarding this. I have no idea what the current state of user contributed docsets is in Zeal.
