### ISSUE TITLE
Bug: Pale DocSet Icons

### ISSUE THREAD

**Issue by sanssecours** [Kapeli/Dash-User-Contributions#1909]
👋 Hi,

it looks like some process modifies the icons for DocSets. At least the icon for the [Elektra DocSet](https://github.com/Kapeli/Dash-User-Contributions/blob/master/docsets/Elektra) looks much paler in Dash (left), than the one I added to the repository (right):

<img width="839" alt="elektra" src="https://user-images.githubusercontent.com/691989/40621038-8183ac20-629b-11e8-9ac0-948e5194e54c.png">

I noticed that the icon for the [Fish DocSet](https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/fish) seems to have the same problem.

# System Information

- Dash `4.1.7`
- macOS `10.13.4`

**Comment by Kapeli** [comment]
Thanks for letting me know about this. I've fixed it.

**Comment by Kapeli** [comment]
Actually looks like I didn't fix it. They display correctly now in Preferences > Downloads > User Contributed, but they're still faded when you install the docset.

I'll have a look tomorrow.

**Comment by Kapeli** [comment]
This will be fixed in the next Dash update. I couldn't fix it server-side 😞

**Comment by sanssecours** [comment]
Seems like a recent update reintroduced this bug:

<img width="252" alt="dash sidebar" src="https://user-images.githubusercontent.com/691989/44459637-aac94100-a60a-11e8-8ea5-90b3e51a05bb.png">


. The icon looks correct inside “Preferences…” though:

<img width="820" alt="preferences" src="https://user-images.githubusercontent.com/691989/44459692-d51afe80-a60a-11e8-9858-6f7c747ce40d.png">

.

**Comment by Kapeli** [comment]
I'm not able to replicate it. Did you try to reinstall the docset? It might be using the old icon.

**Comment by sanssecours** [comment]
Thank you for the quick reply.

> Did you try to reinstall the docset? 

Yes. I just removed it and installed it again. The symbol looks incorrect in Finder too:

<img width="696" alt="docset icon" src="https://user-images.githubusercontent.com/691989/44464521-4c588e80-a61b-11e8-96cb-5bb8041de848.png">

.

**Comment by Kapeli** [comment]
Weird. What macOS and Dash version are you using?

**Comment by sanssecours** [comment]
> What macOS and Dash version are you using?

Dash `4.2.0` on macOS `10.13.6`

I just reinstalled the [DocSet for Fish](
https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/fish). Now the sidebar of Dash shows two pale icons:

<img width="250" alt="dash sidebar" src="https://user-images.githubusercontent.com/691989/44465219-3fd53580-a61d-11e8-90b7-b37bbf8abbc6.png">


.

**Comment by Kapeli** [comment]
I'm not able to replicate the issue using the same macOS and Dash version.

Can you think of anything that might be different with your Mac? Are you sure you're not using an older version of Dash?

**Comment by sanssecours** [comment]
> Can you think of anything that might be different with your Mac?

Not really.

> Are you sure you're not using an older version of Dash?

After I downloaded the latest version of Dash (`4.4.0`) it worked. Thank you for your help 💖. I am kind of puzzled why Dash did not update itself, though…

**Comment by Kapeli** [comment]
Ah, sorry about that. I read the version you mentioned previously as `4.4.0` so I thought you were on the latest one.
