### ISSUE TITLE
Unable to create doc2dash feed with multiple entries inside

### ISSUE THREAD

**Issue by ssbarnea** [Kapeli/Dash-User-Contributions#1920]
Because number of packages build can easily become  huge, I attempted to create a consilidated all.xml feed file for all of the, 

See http://s3.sbarnea.com/docsets/all.xml

Sadly, it appears that Dash is unable to load these feeds. What can we do to fix this?

Please note that for each individual docset I have both the `.tgz` and the `.xml` file, at same location.

I aim to build a `Python Docset` collection with lots of modules fully automated, so I will need some guidance on how to integrate this with Dash in an usable way (so people could install the entire "bundle" as easy as possible).

**Comment by Kapeli** [comment]
This is not supported. Only one docset per feed.

Alternatives are:
1. Submit your docsets to this repo, as user contributed docsets - https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset
2. If you plan on supporting **all** Python modules, I could add a separate option in Dash, like Preferences > Downloads > Python Docsets which would install these docsets only
