### ISSUE TITLE
New DocSet files (too large)

### ISSUE THREAD

**Issue by chris4gl** [Kapeli/Dash-User-Contributions#1939]
Hello,

I have new docset files for OpenEdge (11.5, 11.6 and 11.7).  I checked in the other files required, but these were over the 100MB github limit (they are about 140-150).  Can you let me know where to send them in?

I also have an older docset for OpenEdge checked in that should be removed.

Thanks,
Chris

**Comment by Kapeli** [comment]
You need to upload the docset somewhere (e.g. Dropbox) and send me the link.

Please mention the download links in the issue where you submit the update for the docset itself. I'll close this issue and we'll continue there.
