### ISSUE TITLE
Request: Unreal Docset

### ISSUE THREAD

**Issue by kassane** [Kapeli/Dash-User-Contributions#2020]
Is it possible to add this complete documentation?
[Unreal Doc](https://docs.unrealengine.com/en-us/Programming)
[Unreal API](https://api.unrealengine.com/INT/API/)

**Comment by shahasad78** [comment]
I too have been wanting this.  There used to be a tool that converted the Unreal documentation's CHM file.  but the newer versions of UE4 removed the chm file.

**Comment by brunobely** [comment]
Also after this!  Unity's docs in Dash look great, would be nice to have UE4's as well
