### ISSUE TITLE
Request: Bulma

### ISSUE THREAD

**Issue by unikitty37** [Kapeli/Dash-User-Contributions#2093]
https://bulma.io/documentation/

It looks like dashing can get you most of the way there, though the colours are wrong in dark mode (the grey shades on the Typography helpers page are inverted for one thing). Not sure of the best way to fix that, especially on Mojave where the only way to get Dash into light mode seems to be to change the setting for the entire OS :)

**Comment by godbout** [comment]
bulma is now up to date with 0.9.x. enjoy 🌿️
