### ISSUE TITLE
Vulkan docs extremely slow

### ISSUE THREAD

**Issue by warmwaffles** [Kapeli/Dash-User-Contributions#2132]
The current vulkan docs are extremely slow due to it being one big html file.

Instead it should probably use the https://www.khronos.org/registry/vulkan/ the  [API Reference Pages](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/)

**Comment by Kapeli** [comment]
//cc @antiagainst

**Comment by antiagainst** [comment]
Yeah, originally the Vulkan spec does not have a really good chunked version. I think that gets better now. I can look into switching to the chunked version.

**Comment by warmwaffles** [comment]
@antiagainst that would be awesome.
