### ISSUE TITLE
ghc.io is no longer available in Haskell.docset

### ISSUE THREAD

**Issue by singularitti** [Kapeli/Dash-User-Contributions#2158]
The main Haskell.docset provides an online REPL in the past: https://ghc.io. However, this domain is no longer what it used to be. Could you please disable the little triangle on the docset which redirects to this URL?
<img width="234" alt="haskell" src="https://user-images.githubusercontent.com/25192197/49623618-689af400-f99c-11e8-8d86-6d582711624f.png">
<img width="649" alt="error" src="https://user-images.githubusercontent.com/25192197/49623652-8700ef80-f99c-11e8-93ff-5f0acbd2d10b.png">

**Comment by Kapeli** [comment]
Thanks for letting me know about this. I'll fix it ASAP.
