### ISSUE TITLE
Pytorch 0.4.1 doc page shows "unstable" while it's not

### ISSUE THREAD

**Issue by kkew3** [Kapeli/Dash-User-Contributions#2182]
Hi. I downloaded pytorch 0.4.1 dashdoc. The doc page it opens says:

> You are viewing unstable developer preview docs. Click here to view docs for latest stable release.

Apparently 0.4.1 was stable a long time ago. I suspect dashdoc is using an old link to the unstable official pytorch doc published before the release of 0.4.1. I feel it might be better to have an update. Thank you so much.

**Comment by Kapeli** [comment]
// cc @taketwo

**Comment by taketwo** [comment]
Not sure why the page says "unstable" but I can confirm that I've generated the documentation from released 0.4.1 sources.

That said, an update is indeed needed since 1.0.0 was released since then. I'll send a PR some time soon.

**Comment by taketwo** [comment]
Actually, 1.0.0 docs were already contributed (#2159), so this may be closed.
