### ISSUE TITLE
css file not loaded on Windows

### ISSUE THREAD

**Issue by schmidh** [Kapeli/Dash-User-Contributions#2210]
The newly created docset for Perl 6 does not render well on Windows because the css file is not loaded.

[Windows renders incorrectly](https://github.com/schmidh/Perl6-Dash-Docset-Generator/issues/1)

**Comment by Kapeli** [comment]
Zeal is not made by me, so if it's a Zeal issue there's nothing I can do. My best guess is the docset has special characters in its paths which Windows doesn't handle correctly. Please consider opening an issue in Zeal's GitHub repo.

**Comment by schmidh** [comment]
Sorry, my bad.
