### ISSUE TITLE
docsetcontrib & Ubuntu

### ISSUE THREAD

**Issue by schmidh** [Kapeli/Dash-User-Contributions#2212]
Is the binary docsetcontrib also available on Ubuntu? Are the sources open?

**Comment by Kapeli** [comment]
It's not. It's written in Objective-C so I don't think there's any way to get it to run on Linux.

The source is not open, but I can send it to you if you email me.

**Comment by yo-ga** [comment]
Is it possible to refactor docsetcontrib and then open the sources?
I am full of curiosity about how it verifies.
