### ISSUE TITLE
Update Jest

### ISSUE THREAD

**Issue by KBoyarchuk** [Kapeli/Dash-User-Contributions#2216]

**Comment by Belco90** [comment]
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/2677072/53019657-89300180-3455-11e9-8335-aabdd18863b5.png">
Jest doc is broken after they moved their [doc to the new website](https://jestjs.io/blog/2019/01/25/jest-24-refreshing-polished-typescript-friendly#new-website).

**Comment by andreineculau** [comment]
poke @Kapeli @chinesedfan

PS: @KBoyarchuk "fix" is the word, not "update" 😜

**Comment by andreineculau** [comment]
meanwhile you can pin jest to the older 23.1.0

**Comment by chinesedfan** [comment]
That's strange. I am using Dash v4.6.1(730) and everything looks well, even with uninstalling and installing again.

![dash](https://user-images.githubusercontent.com/1736154/53422461-7bace580-3a1a-11e9-8d7e-3bbb22b65a83.gif)

**Comment by andreineculau** [comment]
I'm experiencing the problem on 4.6.2 (740)

**Comment by andreineculau** [comment]
I would have liked to downgrade to 4.6.1 and see if there's a change, but I can't figure out how to do that.

**Comment by Kapeli** [comment]
I'm not able to replicate the issue in Dash 4.6.2 and Jest 24.1.0 (installed from Preferences > Downloads > User Contributed).

The Jest docset is not really optimised for offline use and it loads some resources online, so maybe you're blocking some network requests and that's causing the page to fail to load?

Can you try to press CMD+B to open the page in your browser? Does it work there?

Can you think of anything special for your Mac? Maybe a case-sensitive file system?

**Comment by andreineculau** [comment]
Hmm, pressing CMD+B opens the page in the browser, and all is good there.
But not in Dash...
And you know what the problem is?... Width! The Jest website switches to
some mobile layout if width is less than X, and it just becomes a 99% white
page at that point :(

Good to close, and some issue should be opened on the Jest website side...
#facepalm

**Comment by andreineculau** [comment]
actually if I go to the Jest website all is good.
So it is actually something on the Dash side.

OK e.g. https://jestjs.io/docs/en/expect.html#tobeclosetonumber-numdigits
NOT OK e.g.
http://127.0.0.1:49321/Dash/xfpayytj/jest/docs/en/expect.html#tobeclosetonumber-numdigits
Tested both in Safari and Chrome.

**Comment by chinesedfan** [comment]
@andreineculau Nice digging! It fails in 13-inch Mac, but works in 15-inch. Simple workaround is changing the width of Dash's left menu. I will try to fix it this week.

**Comment by Belco90** [comment]
@andreineculau resizing the dash window definitely works for me:

<img width="1556" alt="image" src="https://user-images.githubusercontent.com/2677072/53481853-3fab6c00-3a7e-11e9-930c-2bc3c2d7bd52.png">

So the problem is related to the width of the website for sure.

**Comment by andreineculau** [comment]
I can confirm the problem is fixed. Thanks!
