### ISSUE TITLE
docset: slim framework (php)

### ISSUE THREAD

**Issue by CodeBrauer** [Kapeli/Dash-User-Contributions#223]
http://docs.slimframework.com/

I tried to follow the tutorial, but I don't know how to add the HTML things into the sqlite-file.

Maybe somebody want to do this?

**Comment by pfefferle** [comment]
I've build one: https://github.com/pfefferle/dash-slimframework

**Comment by Kapeli** [comment]
@pfefferle Please [contribute it](https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset) if you can.

**Comment by pfefferle** [comment]
Sure, will do!
