### ISSUE TITLE
AWS CloudFormation Templates docs are out of date and the generator is broken

### ISSUE THREAD

**Issue by phene** [Kapeli/Dash-User-Contributions#2260]
The AWS CloudFormation Template docs are quite out of data and unfortunately the generator is now broken due to some significant structural changes to the docs made by AWS. Consider removing support for these as the https://github.com/pdhodgkinson/AWSCloudFormationTemplateReference-dash-docset is likely a dead project.

**Comment by majwhite** [comment]
@phene - I have raised https://github.com/Kapeli/Dash-User-Contributions/pull/2280 to update the docset in Dash - now that the PR against the Docset generator has been merged.
