### ISSUE TITLE
Update docs of Tensorflow and PyTorch

### ISSUE THREAD

**Issue by Thesharing** [Kapeli/Dash-User-Contributions#2275]
The version of Tensorflow is 1.13.0 and 2.0 is under preview, but the docs on dash still remain 1.9.0.

Same for PyTorch.

**Comment by Kapeli** [comment]
// cc @fossil12 @ppwwyyxx @solidfox @iamaziz @Time1ess @JiamingSuen @reuben @taketwo

**Comment by starplanet** [comment]
The stable version of Tensorflow is 2.1, but the docs on dash still remain 1.15.

**Comment by reuben** [comment]
TF 2.x broke the API significantly so there probably needs to be a split (akin to Python 2 vs 3) for docs, so that both the old and the new API are available. The doc generation setup has also changed a bit, but I don't expect it to be a major problem. I'll try to take a look when I have some time.

**Comment by ppwwyyxx** [comment]
I agree that having a split would be good. Many people still use TF 1.x and recently there are complains for better TF 1.x docs (https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/ubiq9tzms7s).

The code https://github.com/ppwwyyxx/dash-docset-tensorflow I wrote to generate 1.x docs probably won't work for 2.x though, given how much their HTMLs have changed.

**Comment by reuben** [comment]
TF 2.1 docs are now available!

**Comment by hologerry** [comment]
Latest PyTorch and torch related vision, text, audio docs are now available!
