### ISSUE TITLE
Javascript docset links to Statements

### ISSUE THREAD

**Issue by carestad** [Kapeli/Dash-User-Contributions#2305]
Should mention I use Zeal, but the problem should lie within the docset itself.

When looking up `let` og `const`, which both are located under `Web/JavaScript/Reference/Statements`, they will not show. Manually manoeuvring with the  breadcrumbs on the top of the MDN page will lead me to the `JavaScript reference` page, where `let` and `const` are listed, and where I can copy the (local) URL.

If I open this in my browser, they do not exist. Manually removing parts of the URL to try and hit the first available directory leads me to:

`file:///home/alexander/.local/share/Zeal/Zeal/docsets/JavaScript.docset/Contents/Resources/Documents/developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/`

where I can see the a `statements` folder, but it is stored with a lower-case `s`, while the links to it are in captail S, for instance:

`file:///home/alexander/.local/share/Zeal/Zeal/docsets/JavaScript.docset/Contents/Resources/Documents/developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let.html`

Another folder also has a lower-case first letter ther, `functions` and it appears that the info page about arrow functions etc. are also broken as they link to `file:///home/alexander/.local/share/Zeal/Zeal/docsets/JavaScript.docset/Contents/Resources/Documents/developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions.html`

It is quite possible these bugs exist for other sections of the MDN Javascript docset as well, but these were at least the first ones I discovered.

**Comment by Kapeli** [comment]
See https://github.com/zealdocs/zeal/issues/1009 and https://github.com/zealdocs/zeal/issues/1009#issuecomment-429325244 specifically.
