### ISSUE TITLE
scikit-learn Latex math markup

### ISSUE THREAD

**Issue by dpitic** [Kapeli/Dash-User-Contributions#2312]
I'm having problems rendering Latex markup when displaying scikit-learn documentation in Dash.  It renders correctly in Safari.  I've attached a screenshot from Dash.
![image](https://user-images.githubusercontent.com/4505681/55328805-c90bef00-54bf-11e9-85a5-554c74509ae1.png)

**Comment by Kapeli** [comment]
JavaScript has been disabled for this docset (`isJavaScriptEnabled` is set to `false` in Info.plist). Setting it to true might fix it, but might break something else.

// cc @iamaziz, @jaypeedevlin, @tafkas, @jnothman

**Comment by jnothman** [comment]
I wouldn't expect it to break anything else.

**Comment by coldJune** [comment]
I can't find a label named `isJavaScriptEnabled` in Info.plist

**Comment by coldJune** [comment]
> JavaScript has been disabled for this docset (`isJavaScriptEnabled` is set to `false` in Info.plist). Setting it to true might fix it, but might break something else.
> 
> // cc @iamaziz, @jaypeedevlin, @Tafkas, @jnothman

I can't find a label named isJavaScriptEnabled in Info.plist

**Comment by Kapeli** [comment]
It's there...

<img width="566" alt="Screenshot 2019-04-04 at 17 54 32" src="https://user-images.githubusercontent.com/1445635/55569941-bdf4d100-5702-11e9-8550-b451f13b439f.png">

**Comment by jnothman** [comment]
Would you recommend enabling javascript, or making the docs fully offline by displaying math as pngs?

**Comment by Kapeli** [comment]
I was never able to get MathJax to work while offline, so even in the docsets I maintain the LaTeX is rendered only when online.

If you know/find a way to convert the MathJax to PNGs, let me know.

**Comment by jnothman** [comment]
Oh, I was just going to use a python Sphinx switch to render pngs.

**Comment by Kapeli** [comment]
That would be better I think.
