### ISSUE TITLE
Request: ionic 4

### ISSUE THREAD

**Issue by ycshao** [Kapeli/Dash-User-Contributions#2351]
Please update the ionic docset version to 4 https://github.com/ionic-team/ionic/releases/tag/v4.3.1

**Comment by Kapeli** [comment]
I plan on doing this, but as the doc format has changed, it's going to take a while.

Please note that this repo is for user contributed docsets, not for the ones maintained by me. For the docsets maintained by me, please [email me](https://kapeli.com/contact).
