### ISSUE TITLE
Request: Rust crates docs from Docs.rs 

### ISSUE THREAD

**Issue by vanthiyathevan** [Kapeli/Dash-User-Contributions#2364]
It would be nice to have docs rust crates from 
https://docs.rs
https://docs.rs/about

**Comment by Kapeli** [comment]
Check out https://github.com/rust-lang/docs.rs/issues/174

**Comment by syphar** [comment]
@Kapeli is there any news about having rust crate docs in dash? I would love to have it. 

I know about https://github.com/rust-lang/docs.rs/issues/174 and https://github.com/rust-lang/docs.rs/issues/1004 , 

while currently I'm not sure if that's not too much effort only for offline download. 

What are the requirements for Dash? 

Just the package docs as HTML? Only for the most recent version? Or all versions of the package?

**Comment by Kapeli** [comment]
There are no news. There's nothing I can do without a way to download the docs.

Just the docs as HTML, yes. Preferably for all versions, but just the most recent stable version is also ok.

**Comment by CandySunPlus** [comment]
@Kapeli Is there any new progress on this issue now, looking forward to using this feature

**Comment by syphar** [comment]
Looking at https://github.com/rust-lang/docs.rs/issues/174#issuecomment-1413071162 , there is definitely progress :)
