### ISSUE TITLE
Update Ansible docset

### ISSUE THREAD

**Issue by Thulium-Drake** [Kapeli/Dash-User-Contributions#2387]
Hi folks,

The Ansible has been outdated by the release of 2.8.0. Can you please update it?

Thanks!

**Comment by Kapeli** [comment]
Thanks for letting me know about this. I'll update it ASAP.

**Comment by Thulium-Drake** [comment]
Would you mind sharing the recipe used to create the docset? :-) I'd like to have multiple versions in my Zael, but when building the docs from source, it doesn't index that well...
