### ISSUE TITLE
Request: AWS Redshift

### ISSUE THREAD

**Issue by rcoup** [Kapeli/Dash-User-Contributions#2388]
AWS Redshift developer guide would be great to get in — SQL-wise it's substantively different to PostgreSQL in all sorts of tricksy ways.

Markdown source: https://github.com/awsdocs/amazon-redshift-developer-guide
HTML: https://docs.aws.amazon.com/redshift/latest/dg/index.html

There's a lot of AWS docs available at https://github.com/awsdocs, so potentially if the markdown from/for one got down it'd be straightforward to pull others together as well.

**Comment by rcoup** [comment]
Happy to flick someone some $ to build this, email me at robert.coup@koordinates.com if you're interested.

**Comment by postalservice14** [comment]
@rcoup sent you an email - I can do this for ya.

**Comment by postalservice14** [comment]
Done.  See PR #2411
