### ISSUE TITLE
WordPress docset - file not found error

### ISSUE THREAD

**Issue by dennyf** [Kapeli/Dash-User-Contributions#2444]
I'm getting a File Not Found error for all entries in the WordPress docset:

<img width="936" alt="dash" src="https://user-images.githubusercontent.com/901213/61685335-c7608280-ad5f-11e9-8ac8-a91e7c35e134.png">

I opened the docSet.dsidx file and it doesn't seem that the path is set correctly, for example:

```<dash_entry_name=comment_max_links><dash_entry_originalName=comment_max_links><dash_entry_menuDescription=comment_max_links (Codex)>codex.wordpress.org/Option_Reference.html#//apple_ref/Option/comment%5Fmax%5Flinks```

Here is a screenshot:

<img width="1106" alt="docset" src="https://user-images.githubusercontent.com/901213/61685436-245c3880-ad60-11e9-9cf6-e0fdafce1496.png">

I tried reinstalling the docset, but it didn't make any difference. 
Thanks

**Comment by Kapeli** [comment]
The latest WordPress docset does not support Dash 2. Please consider upgrading to Dash 4.
