### ISSUE TITLE
Automated submission of large docsets

### ISSUE THREAD

**Issue by heilerich** [Kapeli/Dash-User-Contributions#2523]
A docset I am managing has just hit the 100 MB mark with its latest update. I read about your usual process for such docsets (uploading it somewhere and then providing a link in an issue/PR), but since I automated the whole process of docset generation and submission as much as possible I was wondering if we could also do something about the submission of large docsets that is a little more automation friendly?

Maybe we could use `git-lfs` or maybe submitters could provide a placeholder file instead of the `.tgz` archive which just contains the download link so you can automatically download the large docset in your CI process?

Of course I could also do your usual process, but I would rather build something nice than doing one extra step of manual labor each time the docs are updated ;)

**Comment by Kapeli** [comment]
Couldn't you automatically upload the docset somewhere and automatically include the link in the pull request somewhere?

I'm getting very very few pull requests containing large docsets so it's not worth automating on my end.

**Comment by heilerich** [comment]
Okay, whatever works best for you 👍🏻 I‘ll find a solution.
