### ISSUE TITLE
three.js docset with examples compressed over 240m, how to contribute?

### ISSUE THREAD

**Issue by steve3d** [Kapeli/Dash-User-Contributions#2545]
the current three.js docset is very old one, so I build a new one, and of  course with all the examples, the docset is 374m, and over 250m in tgz format, there is no way to upload to github.

so how can I contribute?

**Comment by Kapeli** [comment]
Please make all the changes you need to the repo (i.e. update the `docset.json`), without actually including the docset.

Upload the docset anywhere you want and submit a pull request and mention the URL where I can download the docset.
