### ISSUE TITLE
scikit-learn document is outdated

### ISSUE THREAD

**Issue by lazywei** [Kapeli/Dash-User-Contributions#256]
Hi, the sklearn doc in Dash is 0.14, while the latest version should be 0.15.
Anyone could help with updating the doc? Or anyone can give me a hint how I can translate the http://scikit-learn.org/stable/documentation.html into Dash's flavor format?

**Comment by ADB991** [comment]
What's the status on this?

**Comment by iamaziz** [comment]
see #1116
