### ISSUE TITLE
GitHub docsets can't search mzlogin/chinese-copywriting-guidelines

### ISSUE THREAD

**Issue by ripperhe** [Kapeli/Dash-User-Contributions#2570]
GitHub docsets can't search mzlogin/chinese-copywriting-guidelines

mzlogin/chinese-copywriting-guidelines
https://github.com/mzlogin/chinese-copywriting-guidelines

![Jietu20191109-183635](https://user-images.githubusercontent.com/13943595/68527249-e17a9c80-031f-11ea-957d-16d44502cacc.png)

**Comment by Kapeli** [comment]
Seems to be a GitHub issue - https://api.github.com/search/repositories?q=chinese-copywriting-guidelines.

**Comment by ripperhe** [comment]
@Kapeli OK, thank you!
