### ISSUE TITLE
Update React Native docs to 0.61

### ISSUE THREAD

**Issue by codecog** [Kapeli/Dash-User-Contributions#2583]
Latest stable release is currently 0.61 but showing 0.57 on the app.

Can we have an update for this please?

http://facebook.github.io/react-native/versions

**Comment by mnmaraes** [comment]
Never maintained a docset here before, but would be willing to do so, provided some guidance

**Comment by mnmaraes** [comment]
Tried doing some work on this today. It seems like the script used to export the docset is out of sync with how the website is laid out. Will try to do some more looking into this later. Don't really know what I'm doing, though, so it might take a while

**Comment by codecog** [comment]
@mnmaraes how did you go?

**Comment by mnmaraes** [comment]
Still on it. Haven't had as much time to work on it lately, though. 

Just to make it available to everyone who doesn't want to wait for my schedule to clear up. The work consistis in updating: https://github.com/dash-docs-community/react-native-dash to the new site layout.

As I remember the issues is in  running `node src/createSectionJSON.js`. It fails to index the sections (returning an empty array)

**Comment by mnmaraes** [comment]
Done: https://github.com/Kapeli/Dash-User-Contributions/pull/2669
And: https://github.com/dash-docs-community/react-native-dash/pull/4

Happy to keep it up to date moving forward. There are a couple more things to do, like adding Component props to the navigation menu, but this should do for now, I think
