### ISSUE TITLE
Request: Sails.js

### ISSUE THREAD

**Issue by moul** [Kapeli/Dash-User-Contributions#261]
Here is the documentation: http://sailsjs.org/#/documentation/

**Comment by ddelrio1986** [comment]
Please add this!

**Comment by byCedric** [comment]
+1 for adding Sails.js documentation

**Comment by jackmasa** [comment]
+1

**Comment by robbiet480** [comment]
:+1:

**Comment by HERRKIN** [comment]
+1

**Comment by ablipan** [comment]
+1

**Comment by manuel-reil** [comment]
+1

**Comment by epitaphmike** [comment]
In the works. Phase 1 (85% complete) is the core concepts, Phase 2 will include the reference section.

**Comment by LizzyBradley** [comment]
@Kapeli Sails.js was added in Version 1.3.1 (Nov 2, 2015).

**Comment by Kapeli** [comment]
Thanks @LizzyBradley 👍
