### ISSUE TITLE
Unreal Engine 4 docset

### ISSUE THREAD

**Issue by lolleko** [Kapeli/Dash-User-Contributions#2672]
So im pretty much done creating a ue4 docset.

But I won't be able to contribute it, because I will definitely hit githubs size limit.

The size of the docset is around 4.5GB the size of the compressed tar is around 2GB.
I will most likely have to provide it to you another way (like mentioned in the readme).

Summary of docset contents:

c++ API: 1.6gb
Blueprint API (Unreal's visual scripting language): 140mb
Guides, Changelogs...: 600mb
Images: 2.1gb

There is also a PythonAPI which I didn't include because the search dropdown is already struggling with 150k CPP methods. Adding the Python API which is pretty similar to the c++ API would make the search basically useless. And the python API is experimental and only for Editor scripting and therefore not used by many people anyway.

<img width="626" alt="Screenshot 2020-02-19 at 12 37 11" src="https://user-images.githubusercontent.com/4759511/74831578-cacbe480-5315-11ea-9e00-9e5918315c67.png">

Even c++ and Blueprint API together already amount to a lot of pages/entries (see image).

It might make sense to distribute the Python API in an extra docset, separate from the main docs.
This might also make sense for the c++ API because not everyone developing unreal uses c++.

---

One more thing functions/logic blocks in the Blueprint Visual scripting language are referred to as "nodes" (example: https://docs.unrealengine.com/en-US/BlueprintAPI/Ability/AddGameplayCueToOwner/index.html). I currently list them under "function" in the index (see image).

But I think it would be better if a dedicated "node" type/category existed so it is a bit clearer were to find the blueprint nodes.

Since unity will also add a visual scripting language this new "node" type/category could also be used there in the future.

**Comment by Kapeli** [comment]
> I will most likely have to provide it to you another way (like mentioned in the readme).

Sounds good. Open a pull request which adds everything except the actual docset, and include a link to the docset.

> And the python API is experimental and only for Editor scripting and therefore not used by many people anyway

I think it's fine to not include the Python API in any way currently. It's up to you.

> One more thing functions/logic blocks in the Blueprint Visual scripting language are referred to as "nodes"

There's a "Node" type already. It's not listed at https://kapeli.com/docsets#supportedentrytypes because it's not so common, but it should work just fine.
