### ISSUE TITLE
How to convert the build output html to docset file?

### ISSUE THREAD

**Issue by hologerry** [Kapeli/Dash-User-Contributions#2702]
I am trying to generate latest torchvison dataset, with the Makefile from [torchvision](https://github.com/pytorch/vision/blob/master/docs/Makefile) and got the `html` and `doctrees` output in `build`:
<img width="706" alt="Screen Shot 2020-03-26 at 21 13 15" src="https://user-images.githubusercontent.com/11660168/77650605-b3cc8200-6fa6-11ea-91bf-11c7c2d56748.png">
How could I convert the `html` output to a useful docset `torchvision.tgz`?

**Comment by venkatasg** [comment]
I seem to be having a related issue when I try to run `doc2dash` on the `_build/html` directory for [Huggingface Transformers](https://github.com/huggingface/transformers/tree/master/docs). After building using sphinx, I get a similar output as above (with html and doctrees folders inside build) -- however when I run `doc2dash` with the directory `build/html', the resulting docset that I get is empty. Only the HTML shows up in the resulting docset.

Running `doc2dash -A _build/` from within `docs/' doesn't work and throws the following error:

`my_directory/transformers-master/docs/build/" does not contain a known documentation format.`

@hologerry When you run `doc2dash -A build/` do you get the same error? Does running `doc2dash -A build/html` or `doc2dash -A build/doctrees` work?

**Comment by hologerry** [comment]
Thanks for your reply. 
`doc2dash -A build/html --name torchvision` works.
Since I am not quite familiar with the Dash docket generation process, I can not help you to address your issue.
Anyway, thanks for your help.
