### ISSUE TITLE
Request: Lua 5.4

### ISSUE THREAD

**Issue by gingerbeardman** [Kapeli/Dash-User-Contributions#2704]
Lua 5.4 (beta) was released October 2019

http://www.lua.org/work/doc/contents.html

> **Main changes**
> 
> new generational mode for garbage collection
> to-be-closed variables
> const variables
> userdata can have multiple user values
> new implementation for math.random
> warning system
> debug information about function arguments and returns
> new semantics for the integer 'for' loop
> optional 'init' argument to 'string.gmatch'
> new functions 'lua_resetthread' and 'coroutine.close'
> string-to-number coercions moved to the string library
> allocation function allowed to fail when shrinking a memory block
> new format '%p' in 'string.format'
> utf8 library accepts codepoints up to 2^31

**Comment by Kapeli** [comment]
Thanks for letting me know about this. Lua is an officially-supported docset, so I'll add 5.4 to Dash soon.

**Comment by gingerbeardman** [comment]
@Kapeli any idea when this is coming? 

Feels odd for the issue to be closed but the docs still not updated?

Thanks

**Comment by gingerbeardman** [comment]
Any update @Kapeli ?

**Comment by Kapeli** [comment]
It's not a priority currently as it's still in beta. It will be a priority once it becomes stable.

**Comment by gingerbeardman** [comment]
It became stable 2020-06-01
