### ISSUE TITLE
request: svelte

### ISSUE THREAD

**Issue by gavinr** [Kapeli/Dash-User-Contributions#2733]
- https://svelte.dev/
- https://svelte.dev/docs

**Comment by noahlh** [comment]
I'm about to take a long international flight sans WiFi so had some extra motivation to put this together (I'm working on a Svelte project).  This docset includes the core API docs as well as the Tutorial.  I couldn't quite get the REPL working in this first versio, but I'm pretty sure it's doable with some tweaks.  Will explore.  

Hope this is helpful!
