### ISSUE TITLE
Update Ampersand.js docset

### ISSUE THREAD

**Issue by Zearin** [Kapeli/Dash-User-Contributions#277]
Thanks for Dash!  I’ve been using it daily for weeks now, and it is the first documentation app that I really love using.  

There are a few things the Ampersand docset could do with in the next update:

----

* **General Updates:** There have been several minor updates to the Ampersand.js docs that add up to a reasonably-sized update.
* **Missing docs (in `ampersand-state`):**
  * The Dash docs have a heading for `dataTypes`, but no content under it
  * The Dash docs are missing the `collections` property (note that it is plural—**collections**—not to be confused with the singular property `collection`, which Dash *does* include)
* **Guides:** The (non-user contributed) docset for CoffeeScript includes a “Guides” section on the left-hand navigation bar.  It would be helpful if the Ampersand.js docset also included a “Guides” section, corresponding to the guides on Ampersand’s [Learn page](http://ampersandjs.com/learn).

**Comment by Kapeli** [comment]
@remko can you take a look at this if you can? @Zearin, you can also improve the docset yourself if you want.

**Comment by remko** [comment]
Thanks for the report, shall look into it.

**Comment by remko** [comment]
Updated the documentation (which also fixed the missing docs), and added the 'Learn' pages as guides.
See #278

**Comment by Kapeli** [comment]
Thanks @remko. @Zearin please check if everything is ok and let me know if I can close the issue.
