### ISSUE TITLE
question: How Can I update/contribute to a Github generated docset

### ISSUE THREAD

**Issue by ddaza** [Kapeli/Dash-User-Contributions#2795]
For instance It looks like a lot of Github Docset exists and when you download them there are complete sections that are missed or never were added.

### For instance: 
https://github.com/microsoft/TypeScript-New-Handbook

Awesome that it exists:
<img width="684" alt="Screen Shot 2020-05-18 at 2 47 37 PM" src="https://user-images.githubusercontent.com/290254/82253398-894bd500-9916-11ea-8672-c53c6d524bd9.png">

### But there is a lot of info missing: 
This whole folder is not there and parts of other folders are not there.
https://github.com/microsoft/TypeScript-New-Handbook/tree/master/intros

ie. `TypeScript for the Java/C# Programmer`

<img width="743" alt="Screen Shot 2020-05-18 at 2 55 01 PM" src="https://user-images.githubusercontent.com/290254/82253962-99b07f80-9917-11ea-80ac-e1c0a1a42df7.png">

https://github.com/microsoft/TypeScript-New-Handbook/blob/master/intros/TypeScript%20for%20the%20Java%20or%20C%23%20Programmer.md

**Comment by Kapeli** [comment]
GitHub docsets are generated locally on your Mac, they're not pre-generated by someone else like user contributed docsets are. There seems to be a bug in the generation of the docsets. I'll look into it.

If you want to report further issues regarding GitHub docsets, please email me about it.

**Comment by Kapeli** [comment]
This should now be fixed. Please let me know if you notice any other issues.
