### ISSUE TITLE
Update libROSA docset

### ISSUE THREAD

**Issue by jonashaag** [Kapeli/Dash-User-Contributions#2829]
Updated from v0.6 to v0.7.2. See archive attached.

**Comment by jonashaag** [comment]
Ok, I can't attach it here due to file size. Is there a way for me to upload it to CDN? Not sure how update procedure for contributors works...

**Comment by Kapeli** [comment]
Please submit a pull request containing the required changes. If the docset itself is too large you need to upload anywhere you want (e.g. Dropbox) and send me a link.
