### ISSUE TITLE
theano is needed

### ISSUE THREAD

**Issue by speedcell4** [Kapeli/Dash-User-Contributions#287]
http://deeplearning.net/software/theano/library/index.html#libdoc

**Comment by iamaziz** [comment]
Theano is already out there now :] #305

**Comment by speedcell4** [comment]
thank you~‍




------------------ 原始邮件 ------------------
发件人: "Aziz Alto";<notifications@github.com>;
发送时间: 2015年2月10日(星期二) 上午6:52
收件人: "Kapeli/Dash-User-Contributions"<Dash-User-Contributions@noreply.github.com>; 
抄送: "(Lambdell)"<376154626@qq.com>; 
主题: Re: [Dash-User-Contributions] theano is needed (#287)




Theano is already out there now :] #305
