### ISSUE TITLE
Ansible Collections Docsets?

### ISSUE THREAD

**Issue by Thulium-Drake** [Kapeli/Dash-User-Contributions#2911]
Ansible will be including some module documetation that lives in other collections. Will the Dash docset include these?

For the documentation in Web form, please see: https://docs.ansible.com/ansible/2.10/collections/index.html

For the announcement, please see: https://groups.google.com/forum/#!topic/ansible-devel/ugrPk9AG7Co

If not, what is the script used to generate the current Ansible docsets from the source? So I can adapt it :-)

**Comment by Kapeli** [comment]
Thanks for letting me know about this. I'll make sure those are included with the Ansible 2.10 docset.
