### ISSUE TITLE
Terraform AWS Provider Missing in recent Docset update

### ISSUE THREAD

**Issue by f3d0r** [Kapeli/Dash-User-Contributions#2953]
The AWS Provider documentation for Terraform is missing in the latest update (published ~8 hours ago)

**Comment by aviflax** [comment]
To be specific: 0.13.1.

For now I’ve downgraded to 0.13.0, which has all the AWS docs.

**Comment by hryamzik** [comment]
Most likely it's better to downgrade to 0.12.28 or 0.12.29. Note that they'll appear as a separate docset.

**Comment by sheldonhull** [comment]
I was about to open request on this. I'm seeing the results mixed up with other providers in my dash docs. 
Was thinking it it maybe was related to the new provider updates, as they have some newer registry/module stuff. Haven't looked at how this all is gathered but might be part of the problem.

**Comment by abeluck** [comment]
I'm a Zeal user. Could someone advise how to construct the appropriate url to download the older 0.13.0 version?

http://frankfurt.kapeli.com/feeds/zzz/user_contributed/build/Terraform/Terraform.tgz leads to the latest broken 0.13.1one

**Comment by mflopez79** [comment]
Seems to be fixed on 0.13.2 (just got an update)

**Comment by f3d0r** [comment]
Confirmed! Closing this unless the issue resurfaces.
