### ISSUE TITLE
the Apple API Reference is missing the Swift sections

### ISSUE THREAD

**Issue by godbout** [Kapeli/Dash-User-Contributions#3015]
![Technologies___Apple_Developer_Documentation](https://user-images.githubusercontent.com/121373/95681403-3ac70c00-0c12-11eb-924f-a4efda7c444d.jpg)

or is it supposed to be somewhere else?

**Comment by Kapeli** [comment]
Can you tell me where this screenshot is from? I don't recognise the page you're on.

**Comment by godbout** [comment]
oh sorry, i thought you'd recognized where it's from. the page is here: https://developer.apple.com/documentation/technologies?language=objc

i've reached that page through Dash. tried to download the Swift Docset, said it was in the Apple API Reference, downloaded that one. then went through the *Frameworks* entries. they're all there except the Swift ones. so i've just `cmd+shift+B` to open the online page and you've got the link.

**Comment by Kapeli** [comment]
I'm pretty sure the `?language=objc` indicates that you have the Apple API Reference docset set to Objective-C and not Swift. You should be able to find the Swift docs if you switch the docset to Swift.

**Comment by godbout** [comment]
ah shit, yes. i was not aware of that feature of Dash. i downloaded the Docset and was accessing it through Alfred. got it now. it's working. thanks!

**Comment by godbout** [comment]
btw, the inner TOC for that Docset, is it special for Main Docsets handled by you or can we have the same kind?

![the_Apple_API_Reference_is_missing_the_Swift_sections_·_Issue__3015_·_Kapeli_Dash-User-Contributions](https://user-images.githubusercontent.com/121373/95880170-ce7f1080-0da9-11eb-9a3c-660f53eac396.jpg)

when i tried to use different types of entries on mine, then the types of entries are ordered alphabetically, and i think the items within each entries also. i found it not nice to use. i prefer when the inner TOC follows the structure of the page, so i end up making all the entries Section type. but in the Apple Reference API, it's super nice. types of entries and items are following the page structure. any way to do that for user generated Docsets?

**Comment by Kapeli** [comment]
This is possible, but undocumented.

There are several types of "dashtoc":
1. `dashtoc`: the one you're using
2. `unsorteddashtoc`: the same as `dashtoc`, but the entries aren't sorted alphabetically and instead show up in the order they are in the page
3. `dashtoc2`: you add the sections of the ToC and the entries, but the order is the one that's in the page (you can't change the order)
4. `dashtoc3`: same as `dashtoc2`, but you can specify your own arbitrary order

For `dashtoc2` the instructions are:

Do this:
1. Set the DashDocSetFamily key to "dashtoc2"
2. Add anchors like this:

```
<a class="dashAnchor" name="//dash_ref/type/name/isSection (1 or 0)"></a>
```

So, you'd have this when you want to start a section with instance methods:

```
<a class="dashAnchor" name="//dash_ref/Method/Instance Methods/1"></a>
```

And then to add methods:

```
<a class="dashAnchor" name="//dash_ref/Method/some method/0"></a>
```

Inside the section you can have entries of different types.

If you'd like instructions for `dashtoc3`, let me know and I'll write them.

**Comment by godbout** [comment]
ah! very nice.

well, `unsorteddashtoc` would already be better to what i have currently. `dashtoc2` seems the way to go ultimately. i'm not gonna need `dashtoc3`. thanks!

just out of curiosity, any reason why you didn't document that?

**Comment by Kapeli** [comment]
> just out of curiosity, any reason why you didn't document that?

I just didn't get around to it yet 😞, it's a bit hard to explain in the docs without showing screenshots and so on and I just can't find the time for it. I'll try to prioritise it.

**Comment by godbout** [comment]
Dash 6 in the making? 😃️

**Comment by Kapeli** [comment]
> Dash 6 in the making? 😃️

Not yet.

**Comment by godbout** [comment]
well, i'll try to be the first buyer once it's there. i love Dash and your work man. can't live without it. there's a couple of apps that make my days brighter and make me smile every time i use them and Dash is one of them. which is also why i'm having a look at Swift. till now i've been doing web stuff or plugins/workflows/extensions for other macOS apps, but i think in the future i might make some macOS apps myself. small ones, that solve one specific problem and that hopefully bring a smile, laugh, and productivity to users. so, thanks again for the great app, the great work, and the inspiration!

**Comment by Kapeli** [comment]
Thanks a lot for the kind words! I'm looking forward to see what you'll make ❤️

**Comment by godbout** [comment]
> Thanks a lot for the kind words! I'm looking forward to see what you'll make ❤️

Dash 7. 

🤣 just kidding. have a good time!

**Comment by godbout** [comment]
hey, sorry to bother you with that one again, but it seems the Docset is not up to date?

for example, check the `Stepper` entry in Dash, and then run the Online Redirection. you'll see that the doc is way different. thanks!

**Comment by Kapeli** [comment]
Dash uses the docs from within Xcode (the version of Xcode to which your `xcode-select -p` points to). Are the docs different in Xcode than Dash?

The online docs are almost always better than the Xcode docs. My assumption is that they're handled by 2 different teams at Apple.

**Comment by godbout** [comment]
shit you're right. this is so fucking dumb 😂️
to be honest i haven't been impressed by Xcode so far. will probably switch back to Sublime and some custom build when i'm more familiar APIs.

thanks again!

**Comment by godbout** [comment]
> Thanks a lot for the kind words! I'm looking forward to see what you'll make ❤️

project settled. i don't know where to start. i have no idea if it's possible. but here we go.

**Comment by godbout** [comment]
> Thanks a lot for the kind words! I'm looking forward to see what you'll make ❤️

OK SORRY FOR THE NOTIFICATION BUT ALSO NOT SORRY BECAUSE IF YOU"RE STILL INTERESTED TO KNOW WHAT I"M BUILDING it is starting: https://www.youtube.com/watch?v=tsqNhX3TelE
