### ISSUE TITLE
Header issue in Kotlin Docset

### ISSUE THREAD

**Issue by iamthen0ise** [Kapeli/Dash-User-Contributions#3030]
Hi! Tried Dash lately. Love it, but there's an issue with Kotlin docset. The header occupies all my screen. 
<img width="1312" alt="Снимок экрана 2020-10-23 в 13 44 15" src="https://user-images.githubusercontent.com/1730030/96994851-f7d03700-1535-11eb-9353-1f86fcca7f75.png">

Is there any way to solve it? Thank you!

**Comment by Kapeli** [comment]
Seems to be a CSS issue inside the docset. Adding `.global-header {display:none}` should fix it.

@pthariensflame any chance you could fix this?
