### ISSUE TITLE
Newer ns-3 docsets too big.

### ISSUE THREAD

**Issue by tnull** [Kapeli/Dash-User-Contributions#3060]
While in the past I managed to keep the ns-3 docsets under github's 100MB limit by disabling `dot` graphs, it seems that this does not work for ns-3.31 and above.

In fact I have two docsets (ns-3.31 and ns-3.32) ready, however, they slightly surpass the 100MB mark. Is there another way I can upload these and maybe only provide the `docset.json` via a pull request?

**Comment by Kapeli** [comment]
Yes. Submit a pull request with just the `docset.json` and in the pull request comment include a link (e.g. Dropbox) to where I can download the docsets from.
