### ISSUE TITLE
Docset generation with ARM-based Macs.

### ISSUE THREAD

**Issue by tnull** [Kapeli/Dash-User-Contributions#3075]
So far I relied on Apple's deprecated `docsetutil` retrieved from an old Xcode installation for docset generation. However, this old version likely won't run on upcoming ARM-based Macs. 

Is there any 'plan B' how to build docsets that previously relied on `docsetutil`?

**Comment by Kapeli** [comment]
It should be possible to run `docsetutil` on ARM too, see https://news.ycombinator.com/item?id=25132217#25132679 for a way.
