### ISSUE TITLE
Docset Request: jq

### ISSUE THREAD

**Issue by uc-cjdavis** [Kapeli/Dash-User-Contributions#3087]
It would take ages for me to contribute a docset based on the jq manual so I'm requesting it here.  If there's a backlog, reply indicating as such and I'll hack something out.

jq manual:  https://stedolan.github.io/jq/manual/v1.6/
Building documentation:  https://stedolan.github.io/jq/download/
Relevant section from the link:
> jq's documentation is compiled into static HTML using Python. To build the docs, run pipenv run python3 build_website.py from the docs/ subdirectory. To serve them locally, you can run python3 -m SimpleHTTPServer. You'll need a few Python dependencies, which can be installed by following the instructions in docs/README.md.

Easiest way to get the docs (installing it on MacOS doesn't install the documentation) is to download source from [the repo](https://github.com/stedolan/jq) as a zip, extract and copy the /docs folder where needed.

**Comment by msimav** [comment]
I have created a script for myself and I am willing to contribute the docset.

Meanwhile, the script can be found at https://gist.github.com/msimav/ae9eb41b1262f06bff878a099fe0c3db.

**Comment by wader** [comment]
Hello PR https://github.com/Kapeli/Dash-User-Contributions/pull/3117 adds a jq docset with no external dependecies

**Comment by daviscyd** [comment]
Huge thanks @wader and @msimav

**Comment by wader** [comment]
@daviscyd  👍   there is an update coming also https://github.com/Kapeli/Dash-User-Contributions/pull/3118 ... of course noticed some issues after it got merged

**Comment by wader** [comment]
I kind of feel i'm pushing how far https://github.com/technosophos/dashing is suppose to be used, maybe the way @msimav   builds the index is better if we want something even nicer

**Comment by msimav** [comment]
I just downloaded to test your docset, @wader and I really like function/expression distinction.
