### ISSUE TITLE
translated docs

### ISSUE THREAD

**Issue by MineTheCube** [Kapeli/Dash-User-Contributions#312]
Hi,

I enjoy using your software, but I think that one thing is missing: use translated docs.

For instance, PHP docs exists in french, but Dash has only the english one.. so what about adding locale settings ?

**Comment by Kapeli** [comment]
I don't want to support translated docs as it would be too much work. It would also be sometimes impossible for me to index a docset in a language I don't know.

Please note that you can generate your own docsets - http://kapeli.com/docsets.
