### ISSUE TITLE
Update Ruby docsets to feature Ruby 3

### ISSUE THREAD

**Issue by svoop** [Kapeli/Dash-User-Contributions#3132]
Ruby 3 has been released on Xmas day last year. 🎉 

Thank you for including Ruby 3, in fact, I suggest you use the opportunity to clean up things a little:

* Drop the "Ruby" docset which contains Ruby 1.x only. Both Ruby 1.8 and 1.9 have EOLed a long time ago.
* Rename the "Ruby 2" dockset to just "Ruby" and include Ruby 3 there.

Thanks a bunch!

(I've just sent the same as feedback via the app, but maybe an issue is the more appropriate place for this. Sorry for the dupe.)

**Comment by Kapeli** [comment]
Thanks for the feedback. This repo is for user contributed docsets only, so I'll close this issue.
