### ISSUE TITLE
dash-ignore-dark-mode class not working

### ISSUE THREAD

**Issue by lolleko** [Kapeli/Dash-User-Contributions#3165]
Adding the class does not prevent images from being inverted.

Or am I missing something? 

![Screenshot 2021-02-16 at 16 58 08](https://user-images.githubusercontent.com/4759511/108087890-2b504780-7078-11eb-943b-74ccd42bd6ce.png)

**Comment by Kapeli** [comment]
Can you upload the affected docset somewhere so I can check?

**Comment by lolleko** [comment]
https://drive.google.com/file/d/1nFyOdR0PZnDXE12Cs0gHQtmW8aloREff/view?usp=sharing

**Comment by Kapeli** [comment]
The way `dash-ignore-dark-mode` works is by reverting back the effect Dash applies. If you add it several times or on elements that don't need it you end up actually inverting something that Dash wouldn't invert by default.

Try to remove `dash-ignore-dark-mode` everywhere and add it one at a time to the elements that need it.

The hero image is not inverted by Dash by default and there's no `dash-ignore-dark-mode` needed for it.

**Comment by lolleko** [comment]
I see, thanks!
How does dash decide wether it inverts an image? Or are images not inverted anymore?
I remember that being the case a few versions ago.

**Comment by Kapeli** [comment]
Currently only SVG images are inverted.

**Comment by lolleko** [comment]
What about the brightness change? anyway to turn that off for images?

![Screenshot 2021-02-17 at 16 25 37](https://user-images.githubusercontent.com/4759511/108226061-d3c7df80-713c-11eb-9e1b-d8c92f8265b1.png)
![Screenshot 2021-02-17 at 16 25 43](https://user-images.githubusercontent.com/4759511/108226073-d4f90c80-713c-11eb-9345-33757cdf5ad5.png)

**Comment by Kapeli** [comment]
Nope, sorry. The images are actually inverted with the whole page, and then inverted back to normal, but unfortunately some colors are lost because they overflow. What you see is the best I could come up with after a lot of trial & error.

**Comment by lolleko** [comment]
Okay it seems like that brightness effects gets messed up when the image is within `<picture>` tags:

### Normal:

![Screenshot 2021-02-17 at 20 50 47](https://user-images.githubusercontent.com/4759511/108259944-fc160500-7161-11eb-8177-a4dc9d6c9841.png)

### `<picture><img><img/></picture>`

![Screenshot 2021-02-17 at 20 51 28](https://user-images.githubusercontent.com/4759511/108259959-033d1300-7162-11eb-8755-3dea83083802.png)

### `<img></img>`

![Screenshot 2021-02-17 at 20 50 59](https://user-images.githubusercontent.com/4759511/108259979-09cb8a80-7162-11eb-855f-c83e09d7fa66.png)

I think I can just remove the picture tags. However that's something you might want to look at.
Also #3069 would be really nice because I would portably only need to change a couple colours to create a decent dark mode by hand.
