### ISSUE TITLE
The doc the is not aligned to the query

### ISSUE THREAD

**Issue by hologerry** [Kapeli/Dash-User-Contributions#3261]
When using Alfred to open a query the viewpoint is not aligned to the item:
![image](https://user-images.githubusercontent.com/11660168/115690919-2073a500-a390-11eb-83ab-224c24be21d3.png)
![image](https://user-images.githubusercontent.com/11660168/115690986-341f0b80-a390-11eb-9288-f00906fdebcf.png)

**Comment by Kapeli** [comment]
What docset does this happen with?

**Comment by hologerry** [comment]
PyTorch and PyTorchLightning

**Comment by hologerry** [comment]
This issue does not happen in previous version of Dash, when I creating the PyTorch docset.

**Comment by Kapeli** [comment]
Previous version of Dash and also a previous version of the docset?

**Comment by hologerry** [comment]
Both.
I did not test it on current version of Dash with a previous version of the docset.

**Comment by hologerry** [comment]
Any news?
Could this be fixed in the next version of Dash?

**Comment by Kapeli** [comment]
This isn't a Dash issue as far as I can tell, but a docset issue.

If the current docset works fine with previous versions of Dash, but not with latest, please let me know and I'll investigate further.
