### ISSUE TITLE
Terraform double search results

### ISSUE THREAD

**Issue by hazcod** [Kapeli/Dash-User-Contributions#3307]
Hi!

I have an unusual thing happening for terraform searches.
So I trigger a search via the Alfred integration ‘tf:’ which shows up the item just fine, so I press enter.
But then it shows up twice in the Dash window as seen on the screenshot.
Any idea why? Thank you.

**Comment by hazcod** [comment]
![Uploading dash-double-results.png…]()

**Comment by Kapeli** [comment]
@bartoszj There seem to be duplicate entries in the docset index, the only difference being that some have `/google-beta/` in their path, while others have `/google/`.

**Comment by bartoszj** [comment]
Hello. Sorry for delay. This double search result is "expected". There are two, official, Terraform providers: [google](https://registry.terraform.io/providers/hashicorp/google/latest) and [google-beta](https://registry.terraform.io/providers/hashicorp/google-beta/latest). I know that it could be confused, so in the #3338 I've removed google-beta provider.
