### ISSUE TITLE
MINOR wording error in my lastname

### ISSUE THREAD

**Issue by francoismassart** [Kapeli/Dash-User-Contributions#333]
![credit](https://cloud.githubusercontent.com/assets/704026/6162755/0d798690-b288-11e4-82de-ed007dc0705b.png)
Hello,
just to let you know you made an error on my name: it is *Massart*, not -Massaer-

Thank you

**Comment by Kapeli** [comment]
Nope, you made an error: https://github.com/francoismassart/Dash-User-Contributions/blob/master/docsets/npm/docset.json#L6.

Submit a pull request to fix it when you can :+1:

**Comment by Kapeli** [comment]
Nevermind, I fixed it.
