### ISSUE TITLE
Create For DashLookup repositories

### ISSUE THREAD

**Issue by Imagle** [Kapeli/Dash-User-Contributions#335]
I installed DashLookup, when Export dashlookup as deployable plugin, I got some error, below is error info, Could you help me deal with this? 

/Users/lynn/Documents/workspace-java/.metadata/.plugins/org.eclipse.pde.core/temp/org.eclipse.pde.container.feature/assemble.org.eclipse.pde.container.feature.p2.xml:38: The following error occurred while executing this line:
/Users/lynn/Documents/workspace-java/.metadata/.plugins/org.eclipse.pde.core/temp/org.eclipse.pde.container.feature/assemble.org.eclipse.pde.container.feature.p2.xml:48: The following error occurred while executing this line:
/Users/lynn/Documents/workspace-java/.metadata/.plugins/org.eclipse.pde.core/temp/org.eclipse.pde.container.feature/assemble.org.eclipse.pde.container.feature.p2.xml:24: The following error occurred while executing this line:
/Users/lynn/Documents/workspace-java/DashLookup/build.xml:244: The following error occurred while executing this line:
/Users/lynn/Documents/workspace-java/DashLookup/build.xml:348: Problem: failed to create task or type apitooling.apigeneration
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

The following error occurred while executing this line:
/Users/lynn/Documents/workspace-java/.metadata/.plugins/org.eclipse.pde.core/temp/org.eclipse.pde.container.feature/assemble.org.eclipse.pde.container.feature.p2.xml:48: The following error occurred while executing this line:
/Users/lynn/Documents/workspace-java/.metadata/.plugins/org.eclipse.pde.core/temp/org.eclipse.pde.container.feature/assemble.org.eclipse.pde.container.feature.p2.xml:24: The following error occurred while executing this line:
/Users/lynn/Documents/workspace-java/DashLookup/build.xml:244: The following error occurred while executing this line:
/Users/lynn/Documents/workspace-java/DashLookup/build.xml:348: Problem: failed to create task or type apitooling.apigeneration
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

**Comment by Kapeli** [comment]
This is the wrong repo. Please report this issue here: https://github.com/justinkb/DashLookup.
