### ISSUE TITLE
Provide cheatsheet creation instructions, correct ToC instructions

### ISSUE THREAD

**Issue by holyjak** [Kapeli/Dash-User-Contributions#3432]
Hello! In Dash I see it distinguishes between docsets and cheat sheets. So how does a cheat sheet differ from a normal doc set? How do I make one?

Also, playing with cheatset, I see that the ToC support it generates differs from https://kapeli.com/docsets#tableofcontents in multiple ways:

* No `class="dashAnchor"` on the links
* The format is not `//apple_ref/cpp/Entry Type/Entry Name` but `//dash_ref/Entry Type/Entry Name/1` and, for sub-categories such as Entries which are below Categories: `//dash_ref_<parent entry name>/<entry type>/<entry name>/0`. It also generates for each one a `link` inside the header; ex.: `<link href='//dash_ref/Category/MyCategory1/1'>`

**Comment by Kapeli** [comment]
> So how does a cheat sheet differ from a normal doc set? How do I make one?

They're the same as far as internal workings are concerned. The only difference you could say is that cheatsheets are generated using `cheatset`, while docsets can be generated using anything.

You can generate a cheatsheet using [cheatset](https://github.com/Kapeli/cheatset/blob/master/README.md).

Cheatsheets use a more complicated format of table of contents. In this format, you can define the section names individually. If you want instructions for this format, please let me know.

**Comment by holyjak** [comment]
Thank you! I cannot really use cheatset since I have a HTML as a starting point and convertin that to ruby to generate html is ... painful :) I have tried to copy what cheatset does but not sure how well I succeeded.

Perhaps if you could be so very kind and have a brief look at the docset html I have generated (either the full [docset](https://github.com/holyjak/dash-asciidoc-cheatsheet/releases/tag/2.0.16%2Falpha) or just the index.html itself: https://github.com/holyjak/dash-asciidoc-cheatsheet/releases/download/2.0.16%2Falpha/index.html) and tell me whether I missed something.

I think that explicit instructions would be useful also for other people that cannot use the ruby lib for some reason and want to do it themselves. As I mention above, the general docset instructions seem to diverge from what cheatset actually does.

**Comment by Kapeli** [comment]
`notes` in the cheatset format can contain HTML instead of Markdown as far as I know. Converting should just be copy pasting to the right place.

**Comment by Kapeli** [comment]
Closing this as it's not related to user contributed docsets. Please open an issue in the `cheatset` repo.
