### ISSUE TITLE
Question about URL paths

### ISSUE THREAD

**Issue by skarfacegc** [Kapeli/Dash-User-Contributions#345]
I'm wondering how URL paths are supposed to work.

My database looks like:
```
CREATE TABLE searchIndex(id INTEGER PRIMARY KEY, name TEXT, type TEXT, path TEXT);
```

A sample row is:
```
1120        Test::Able::Planner                   http://metacpan.org/pod/Test::Able::Planner                  Package
```

Test::Able::Planner shows up in the index, but won't load the URL specified in the path.  I think pulling the full set of HTML for CPAN will be north of 250MB which seems a bit large.

**Comment by skarfacegc** [comment]
I'm dumb.  Columns are wrong....  Didn't catch it until now.  Will retry with even more correctness.

**Comment by Kapeli** [comment]
A 250MB docset is perfectly fine. The Mono docset is 1.7 GB. Generally, go for offline support whenever you can.

The next version of Dash will also support archived docsets (i.e. docsets are kept archived and individual files are only unarchived when needed), so that will make large docsets even more ok.

However, are you sure the whole CPAN is only 250MB?

**Comment by keitayabu** [comment]
I have been pay but Dash ask again . I don't know how to use ,so I 'v never used it . I want to know my problem that what I have to do . 
Dash answer is upper grade . ......?   Pay many never use . I do't know how to , 
It's me strange . pay many do thing . So is it good or just ask some mony ?

**Comment by keitayabu** [comment]
I cheat iTune last year I payed 10 Boxs    
It has been change system ? 
Pay and can't finish it mea unusedfl to me ? 
Wash my money .

**Comment by skarfacegc** [comment]
Not at all.  :) A full mirror is 18G (including outdated modules) but I suspect the POD docs are much smaller.  (could be wrong about that though)
