### ISSUE TITLE
mac os 12 dash quit unexpectedly

### ISSUE THREAD

**Issue by gitony0101** [Kapeli/Dash-User-Contributions#3464]
Process:               Dash [29954]
Path:                  /Applications/Dash.app/Contents/MacOS/Dash
Identifier:            com.kapeli.dashdoc
Version:               6.0.7 (980)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2021-10-30 12:13:11.1682 +0800
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x00007ff846821450
Exception Codes:       0x0000000000000002, 0x00007ff846821450
Exception Note:        EXC_CORPSE_NOTIFY

**Comment by Kapeli** [comment]
Please email me about this and include the complete crash report.
