### ISSUE TITLE
Question: Local playground possible?

### ISSUE THREAD

**Issue by stefankolb** [Kapeli/Dash-User-Contributions#3465]
I want to add a playground to a docset, but instead of having a link to an external resource, the playground will be included in the docset itself. How would I reference the playground in `Info.plist`? I know that the key is `DashDocSetPlayURL`, but what would be the string value? So far, I tried the following, but none of these work:

* `demo.html`
* `/demo.html`
* `file:///demo.html`
* `file:///MyDocset.docset/demo.html`

**Comment by Kapeli** [comment]
This is not currently possible. I'll add support for it in the next Dash update.

You should set the path as `demo.html`, where `demo.html` can be found within the `Documents` folder of the docset.

**Comment by stefankolb** [comment]
Awesome, thanks for that. 🙂 

In retrospect, using `demo.html` might not be a good idea, though. `playground.html` sounds like a better fit. What do you think?

**Comment by Kapeli** [comment]
Sorry for the confusion. You can set `DashDocSetPlayURL` to any path you want. `demo.html` was just an example.
