### ISSUE TITLE
Third party Java docsets never seem to work

### ISSUE THREAD

**Issue by sreilly** [Kapeli/Dash-User-Contributions#3492]
The main javaSE docsets work, but trying to install anything from the Third-party source Java Docsets section results in the same error:

Error Installing Docset

An error occured while installing the docset. The error message is: 

Error: Could not find the javadoc index file.

Please contact Dash's developer if you can't recover from this error.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/470762/143073546-b95845c1-b5d4-4da1-af2c-af261fe755e1.png">

Is there any way to load any of these docsets or inspect the docset that is downloaded?

**Comment by Kapeli** [comment]
This is not the right place for this issue, as this repo is for user contributed docsets. You've already contacted me by email regarding this, there's no need to open an issue here.
