### ISSUE TITLE
Updating to latest docsets when contributor is absent

### ISSUE THREAD

**Issue by hbarr** [Kapeli/Dash-User-Contributions#3668]
I came back to Dash after a year of not programming.  I found that some docsets are woefully out of date.
For example,I wanted to update the Electron docset to the latest version, from 2.0.2 to 18.0.3.
However, I cannot find an easy way to do that because the docset Download button only knows a few ancient versions.
The docsets are associated with a named contributor which limits the ability to update.
But if the original contributor disappears and is no longer keeping the docset current, what do we do?

**Comment by Kapeli** [comment]
Anyone can submit a docset update, not just the original contributor. You can generate the docset for the latest version and contribute it.
