### ISSUE TITLE
Request: Swift Language Guide - Add the Language Reference and fix online links, will pay if need be

### ISSUE THREAD

**Issue by capaldo** [Kapeli/Dash-User-Contributions#3671]
So I've tried using the archived repository to try to update the Swift Language Guide but unfortunately, it does not work. 

At this time, the docset runs into two issues:
1. The links to the [Language Reference](https://docs.swift.org/swift-book/ReferenceManual/AboutTheLanguageReference.html) do not work offline. 
2. Trying to open the "Open Online Page" produces an error.  [This](https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html/docs.swift.org/swift-book/LanguageGuide/NestedTypes.html) is the link thats produced when copied.

If someone can manage to fix this and requires money to fix it, name your price and let me know. We would just have to use a third party to confirm that the documentation was in fact updated/fixed.

**Comment by Kapeli** [comment]
// cc @roeybiran

**Comment by roeybiran** [comment]
Working on it!

**Comment by roeybiran** [comment]
Done! #3684

**Comment by capaldo** [comment]
> Done! #3684
> 
> @Kapeli, to fix the online redirection issue, I had changed the `DashDocSetFallbackURL` to just `https://`. Is this problematic?
> 
> > So I've tried using the archived repository to try to update the Swift Language Guide but unfortunately, it does not work.
> 
> @capaldo, what did you try to do exactly? I don't understand.

@roeybiran I saw the edits you made to the script and I definitely over complicated it. Thank you for taking the time to add the reference portion. Let me know if theres a link where I can grab a coffee or something for you. Thank you 🙏.

**Comment by roeybiran** [comment]
That is very kind of you @capaldo, thanks! [Here’s the link](http://paypal.me/roeybiran).
