### ISSUE TITLE
Problems generating a ToC

### ISSUE THREAD

**Issue by jason0x43** [Kapeli/Dash-User-Contributions#368]
The "Generating Dash Docsets" instructions state that a ToC can be generated by adding special "//apple_ref" links to a docset. There seems to be more to it than that, though. I've tried adding tags to a docset as described, then removing and re-adding my docset in Dash's preferences, but Dash never shows a ToC. I've looked through a number of existing docsets that have tables of contents, and they all seem to use different flavors of tags (//apple_ref vs //dash_ref with a variety of types such as "clm"), and all include .dashtoc JSON files, which aren't mentioned anywhere in the instructions.

Is there some relationship that should exist between ToC tag names and search index names?

**Comment by Kapeli** [comment]
> Is there some relationship that should exist between ToC tag names and search index names?

No. None.

Can you upload the docset somewhere so I can look into it and figure out what's going wrong?

**Comment by jason0x43** [comment]
Thanks for taking a look. I uploaded it to https://dl.dropboxusercontent.com/u/721526/DojoN.docset.tbz

It's quite rough at the moment -- there will be much reformatting once I have a better idea of how things should work.

**Comment by Kapeli** [comment]
Your anchors look like this:

```html
<a name="//apple_ref/Property/dijit%2F_AttachMixin._attachEvents">
```

They should be:
```html
<a class="dashAnchor" name="//apple_ref/cpp/Property/dijit%2F_AttachMixin._attachEvents">
```

You're missing the `dashAnchor` class and the `/cpp/` bit in the name.

**Comment by jason0x43** [comment]
Ah, I tried that format before, but at that point I wasn't completely adding and removing the docset from Dash to see if it worked. Success!

I've seen various other formats that work, too, which makes me wonder what exactly the requirements are. The Node.js docset doesn't use the dashAnchor class or "/cpp" in its `//apple_ref` links, but its pages have ToCs. The current Dojo docset uses `//dash_ref_<name>` rather than `//apple_ref` for its links, and they also work. All of the other docsets I looked at also have .dashtoc files. Is the complete ToC format described anywhere (is it related to Apple's HeaderDoc)?

**Comment by Kapeli** [comment]
> The current Dojo docset uses //dash_ref_<name> rather than //apple_ref for its links, and they also work. All of the other docsets I looked at also have .dashtoc files. Is the complete ToC format described anywhere (is it related to Apple's HeaderDoc)?

No.

`.dashtoc` files are used by Dash for iOS because I don't have access to the DOM over there. These files are automatically generated when I upload a docset for iOS. Don't worry about them.

All other styles of defining TOCs are just different flavours that allow different things. For example, the current TOC in the Dojo docset allows for custom section titles (i.e. "Public Methods" instead of just "Methods").

If the current style described at kapeli.com/docsets fits your needs, leave it as-is. If not, let me know what else you need and I'll describe what you need to do.
