### ISSUE TITLE
Update matplotlib docset to latest version (1.4.3)

### ISSUE THREAD

**Issue by iROCKBUNNY** [Kapeli/Dash-User-Contributions#373]
Current version of the matplotlib docset is 1.3.1, please update it to 1.4.3 if possible.

Thanks very much!!!!

**Comment by Kapeli** [comment]
@iamaziz Can you look into this?

**Comment by iROCKBUNNY** [comment]
@Kapeli Thanks for forwarding this message.
@iamaziz Thank you very much!

**Comment by iamaziz** [comment]
@iROCKBUNNY  your very welcome, thanks for pointing out the new version. 

@Kapeli the pull #374 doesn't have the docset, it exceeds GitHub limit 

```
remote: error: File docsets/matplotlib/matplotlib.tgz is 145.56 MB; this exceeds GitHub's file size limit of 100 MB
To https://github.com/iamaziz/Dash-User-Contributions.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/iamaziz/Dash-User-Contributions.git'
```
So, I share it in dropbox here:
https://dl.dropboxusercontent.com/u/12327637/test-files/matplotlib.tgz 

Is there a way to have uploaded from there?

**Comment by iamaziz** [comment]
the pull request does update the README and the json file however

**Comment by Kapeli** [comment]
That's fine. I'll merge and post the update soon.

**Comment by iamaziz** [comment]
Great, thanks.
