### ISSUE TITLE
Request: Matrix

### ISSUE THREAD

**Issue by jaller94** [Kapeli/Dash-User-Contributions#3750]
![Screenshot_2022-09-29_19-17-00](https://user-images.githubusercontent.com/10872136/193098489-5e1e27c0-c045-4a05-bf8a-d9f8590849a3.png)

Matrix is a decentralised, real-time communication protocol. The homepage is https://matrix.org .

Its specification would be a valuable resource to have offline for building clients, servers, bots, bridges and other integrations.

Currently, a new version of the specification is released multiple times a year and usually replaces older versions while staying backwards compatible within major releases.

Root url: https://spec.matrix.org/latest
Repository: https://github.com/matrix-org/matrix-spec

The repository uses the static site generator Hugo.

**Comment by jaller94** [comment]
## Attempt at rendering with Hugo

Instead of creating a copy with the HTTrack Website Copier, I'm looking into how viable it is to build the page with Hugo.

### Making links references

The repository does not use Hugo references, which prevents Hugo from effectively generating links.
Use this find replace Regular Expression (compatible with VS Code) on every file in the `contents` folder:

Find: `\((/[^.]*)/?(#.*?)?\)`
Replace with: `({{< ref "$1$2" >}})`

It searches for Markdown links which don't include a `.` (implying those are static files).
They are replaces with a [Hugo ref](https://gohugo.io/content-management/cross-references/#use-ref-and-relref).
Additional `/` at the end of links are removed, as those break Hugo's algorithm, e.g. `(/foo/#test)` becomes `({{ ref "/foo#test" }})`.

### `config.toml` changes

1. Make all links relative and "ugly", which links the html files directly. This is required when serving files from disk instead a webserver that changes `/foo/` to `/foo/index.html`.

```toml
relativeURLs = true
canonifyURLs = false
uglyURLs = true
```

2. In the section `[params.version]` comment out `status`.
3. In the section `[params.version]` uncomment `major`, `minor` and `release_date`.

### Known issues
* Every link back to the root page is broken. They link to `/` instead of `/index.html`.
* The navigation links link to external pages and are mostly irrelevant for an offline specification. Search for `class="td-navbar-nav-scroll` and remove the `div`, if you want the navigation links removed.

**Comment by jaller94** [comment]
Repo to build the docset on CI:
https://gitlab.com/jaller94/dash-matrix-spec

**Comment by jaller94** [comment]
I've updated my Docset to Matrix Spec v1.4 which was released today.

**Comment by Kapeli** [comment]
Have you considered contributing your docset?

**Comment by jaller94** [comment]
Yes, I'd like to contribute it.

https://gitlab.com/jaller94/dash-matrix-spec/-/issues/2

I'm not exactly sure what needs to be done next.
Sadly, generating a proper search index seems difficult.
The Spec uses Hugo and I guess I'd have to write a custom script to extract headings and URLs to those.
