### ISSUE TITLE
Sidebar should be removed on zig docset

### ISSUE THREAD

**Issue by aiotter** [Kapeli/Dash-User-Contributions#3774]
[zig docset](https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Zig#readme) contains sidebar on the left side.
According to the [contribution guide](https://github.com/Kapeli/Dash-User-Contributions/wiki/Docset-Contribution-Checklist#optional-but-highly-recommended), sidebars is better to be removed.

@kassane is responsible for this docset. How do you think of this?

**Comment by kassane** [comment]
> @kassane is responsible for this docset. How do you think of this?

Oops! I just forgot to remove it.🤦
I will need to edit the HTML by removing the column referring to the page menu.
