### ISSUE TITLE
[Help Needed] Pytorch Lightning Document exceeds 100MB limit

### ISSUE THREAD

**Issue by munhouiani** [Kapeli/Dash-User-Contributions#3790]
Hi, I am the maintainer of the PyTorch lightning document. Unfortunately, the latest document (version 1.6.5) exceeds the 100MB limit, and I couldn't push it to this repo. What options do I have?

**Comment by Kapeli** [comment]
Submit a pull request without the docset in it, and provide a link to the docset (e.g. on Dropbox) within the pull request comment. See https://github.com/Kapeli/Dash-User-Contributions/pull/3361 for an example.
