### ISSUE TITLE
Boost.Hana wrong link

### ISSUE THREAD

**Issue by patlefort** [Kapeli/Dash-User-Contributions#3797]
Same problem as the last time: #2759, Boost.Hana links to Boost.GraphParallel.

Since it's not user contributed, is it still fine to report it here?

**Comment by Kapeli** [comment]
Thanks for letting me know about it. I'll fix it ASAP. It's best if you report issues for contributed docsets directly to me (https://kapeli.com/contact), but here is fine as well.
