### ISSUE TITLE
Expo docset outdated

### ISSUE THREAD

**Issue by jhogervorst** [Kapeli/Dash-User-Contributions#3915]
The [Expo docset](https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Expo) is quite outdated. It’s for version 37, which is from [April 2020](https://blog.expo.dev/expo-sdk-37-is-now-available-dd5770f066a6). The current Expo SDK is already at [version 46](https://blog.expo.dev/expo-sdk-46-c2a1655f63f7).

If it’s no longer being maintained, maybe it would be better to remove it?

**Comment by Kapeli** [comment]
// cc @adrum

**Comment by adrum** [comment]
@jhogervorst This can be closed, as #4266 added versions 40, 44, and 48.
