### ISSUE TITLE
Request: sections in Hex docs

### ISSUE THREAD

**Issue by xxdavid** [Kapeli/Dash-User-Contributions#3953]
Hi, thank you for making Dash. I've been happily using it for years!

I also really love the tremendous support of Hex docsets. The only thing I think is missing is *sections* in the left sidebar. Each module in Elixir has something like an introduction to the module (called *moduledoc*) with information regarding the module as a whole. The moduledoc is usually structured with headings and these are then shown in the left sidebar on hexdocs.pm to ease the navigation (under *Sections*). I think all `h2`s under the `section#moduledoc` are listed there. See for example [GenServer](https://hexdocs.pm/elixir/GenServer.html) or [GenStage](https://hexdocs.pm/gen_stage/GenStage.html) (the latter uses an older version of `ExDoc` thus the page looks a bit different but the `section#moduledoc h2` selector should still hold).

I think the headings could also be listed in the left sidebar of Dash, at the top (above Types). What do you think about it?

**Comment by Kapeli** [comment]
Thanks for suggesting this! I've added support for this.

Please reinstall the docsets you need.

**Comment by xxdavid** [comment]
Thanks! 🙂
