### ISSUE TITLE
Seaborn docs missing some images (included link to oversized fixed docsets)

### ISSUE THREAD

**Issue by paw-lu** [Kapeli/Dash-User-Contributions#4009]
#3951 (created by me) updated the seaborn docs, but is missing some images. I've rebuilt the docs to include all the missing images, but it's over the GitHub size limit.

I've hosted it here for now for a quick fix:

https://drive.google.com/drive/folders/10_9NQaMuo8xzBpWeLRXbFNN52ANpApvy?usp=share_link

I'm trying to think of a better way to do this is the future so that it's more automated. I don't really want to go through the trouble of manually updating to Google Drive and having you download it every time there is a new release (any ideas?).

**Comment by Kapeli** [comment]
I'm not sure. I'm ok with doing it manually on my end, as long as it doesn't update really often (e.g. once every 2 weeks is fine), and maybe there's a way to automate uploading to Google Drive?

Can you upload it as a `tgz` to Google Drive? I've tried downloading it and the docset I'm getting has no CSS, so the pages look wrong.

**Comment by paw-lu** [comment]
> I've tried downloading it and the docset I'm getting has no CSS, so the pages look wrong.

Oh weird, sorry about that. Can confrim it looks okay locally. I'll upload again as `tgz`.

https://drive.google.com/file/d/19QuZ1bn9MDkzHRVFI6JSe5ImoY_LS8fT/view?usp=share_link
