### ISSUE TITLE
C++ Docset cannot find the file specified

### ISSUE THREAD

**Issue by datMaffin** [Kapeli/Dash-User-Contributions#4035]
Hi, 

The C++ docset seems to not always be able to "find the file specified". 
![image](https://user-images.githubusercontent.com/29998721/205837431-5c5ef27d-9b64-4d42-af09-bc331e9841dc.png)

Full text:
> Error opening C:/Users/marvin.dostal/AppData/Local/Zeal/Zeal/docsets/C++.docset/Contents/Resources/Documents/en.cppreference.com/w/cpp/chrono/operator%2522%2522d.html: The system cannot find the file specified

> Failed to load URL file:///C:/Users/marvin.dostal/AppData/Local/Zeal/Zeal/docsets/C++.docset/Contents/Resources/Documents/en.cppreference.com/w/cpp/chrono/operator%252522%252522d.html.
> 
> QtNetwork Error 203

**Comment by Kapeli** [comment]
Please open an issue regarding this in Zeal's GitHub repo.
