### ISSUE TITLE
Atom docset outdated

### ISSUE THREAD

**Issue by bkbooth** [Kapeli/Dash-User-Contributions#407]
I'm the contributor of the Atom.io docset, it's quite outdated now and I don't have the time to keep up with the changes.

Perhaps it might be best to remove this docset for now and I'll take another look at it once they reach a 1.0 version and hopefully the changes to the API slow down a little.

Also happy for anyone else to take over this if they have time/interest.

**Comment by Kapeli** [comment]
I'll leave it alone for now. I might remove it if it bothers anyone in the future. Thanks for the heads up!

**Comment by Kapeli** [comment]
I'll leave this issue open in case anyone wants to take over.
