### ISSUE TITLE
Contributing Cheat Sheets

### ISSUE THREAD

**Issue by strider72** [Kapeli/Dash-User-Contributions#414]
I'd like to contribute a cheat sheet, but I'm a bit confused.  Is the method different for Cheat Sheets as opposed to DocSets?  When I look at the source of some cheat sheets I have installed it appears to have a different file structure than what you recommend in the contribution instructions.

Should I just add a copy of a different cheat sheet to my fork and modify that?

**Comment by Kapeli** [comment]
Cheat sheets have their own repo.

See https://github.com/Kapeli/cheatset#readme for instructions on how to create cheat sheets (it's a lot easier than docsets) and see https://github.com/Kapeli/cheatsheets#readme for instructions on how to contribute a cheat sheet.
