### ISSUE TITLE
Separate docsets for GNU Guile 2 and 3

### ISSUE THREAD

**Issue by lshprung** [Kapeli/Dash-User-Contributions#4202]
Hello. I see that the GNU Guile docset is still at version 2.2. I would like to see version 3 packaged, but recognize it may be beneficial to have docsets available for both GNU Guile 2 and 3. I'm not sure if the best way of accomplishing this would be to have separate docsets or if there is a way to make both versions available via the `versions` directory. Once the best way is determined, I will be happy to create a PR.

**Comment by Kapeli** [comment]
Either way is ok, but I think it's best if GNU Guile would be updated to v3, and v2.2.1 would be copied under `specific_versions` within the same docset.json.
