### ISSUE TITLE
Repo size will continue to grow unless docset archives are eliminated from git history

### ISSUE THREAD

**Issue by jeremy-w** [Kapeli/Dash-User-Contributions#4205]
## Summary
The README says that the intent is to remove the raw docset files and rehost them to a CDN to keep the repo size down. While the docsets/ folder size is being kept down by processing, the raw docsets remain in the git history, so the repo size keeps growing, which means cloning the fork to continue a new docset takes longer.

The top 5 object files represent about 127 MiB.

## Recommendation
Two things come to mind:

* Encourage people to make a shallow clone to work on their docset. Since the actual checkout is quite small, I think this will be speedy. But it's easy for folks to miss, and it's probably not supported by most GUI tools. This is more a user-executed workaround than a fix.
* Scrub the files from the repo history, as explained in GitHub's ["Removing sensitive data from a repository" article](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#purging-a-file-from-your-repositorys-history). This requires history rewriting with a force push. I think if you have the processing script automatically re-scrub the repo each time it runs, you wouldn't need to worry about any PRs that try to merge back in docset archive objects you've already scrubbed from this repo.

## Numbers
As of 2023-03-16, with master at [commit 9238887](https://github.com/Kapeli/Dash-User-Contributions/tree/9238887e0825c30fc72f319006ec1e2c5a5f71b5), docsets/ is only 19M, but .git on a fresh clone is 162M.

I noticed this when I cloned a fresh fork:

```
> git clone https://github.com/jeremy-w/dash-docset-aria.git
Cloning into 'dash-docset-aria'...
remote: Enumerating objects: 18969, done.
remote: Counting objects: 100% (117/117), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 18969 (delta 71), reused 109 (delta 68), pack-reused 18852
Receiving objects: 100% (18969/18969), 150.73 MiB | 17.32 MiB/s, done.
Resolving deltas: 100% (10258/10258), done.
```

I ran `gitlistobjectbysize` from https://gist.github.com/magnetikonline/dd5837d597722c9c2d5dfa16d8efe5b9 and found that the docset tgz files are still in the repo history, which explains the size. The largest 5 objects are:

```
139369e82e92d6fc52e8b61736fc637029fa4051 36341802  docsets/seaborn/seaborn.tgz
07668ccb88ce80765dc844d04c27e06c6b520d85 28121468  docsets/JUCE/versions/7.1.2/JUCE.tgz
685a5dbd89c54ec2fe05a335d69652d6ad9eb5c4 26744298  Powershell.tgz
077e1a02b086c2849ddac6ae1868b1243c74182b 20811396  docsets/XMake/versions/2.6.5/Xmake.tgz
077e1a02b086c2849ddac6ae1868b1243c74182b 20811396  docsets/XMake/Xmake.tgz
```

The middle column is the size in bytes, so these 5 alone amount to about 127 MiB.

**Comment by Kapeli** [comment]
Thanks! I've cleaned the repo and I will make sure it won't grow up in size again.
