### ISSUE TITLE
Support for other compression methods/git LFS for docsets > 100MB?

### ISSUE THREAD

**Issue by jamesoff** [Kapeli/Dash-User-Contributions#4214]
I regularly update the boto3 docset. The most recent version seems to have a new layout (as in, HTML theme) and the tgz archive comes out at about 256MB - much larger than it used to be - which GitHub rejects because it's over 100MB.

GitHub wants me to upload it using LFS, which I'm happy to do if it will work with your workflow?

However, I experimentally made the tar file with zstd compression and it came out at 49MB instead, which would be a win for users downloading updates too. I don't know how Dash handles reading the tar files for docsets, so I don't know if this would be compatible.

How would you like me to proceed?

**Comment by jamesoff** [comment]
Just in case:

```
Dash-User-Contributions/docsets/Boto3 % git push -u origin boto3-2023-03-22
Enumerating objects: 17, done.
Counting objects: 100% (17/17), done.
Delta compression using up to 10 threads
Compressing objects: 100% (12/12), done.
Writing objects: 100% (12/12), 233.19 MiB | 3.02 MiB/s, done.
Total 12 (delta 6), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (6/6), completed with 3 local objects.
remote: error: Trace: ebbe797ef43c868401932b333abb8b96a390addfde334bc4e9265c28b726043e
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File docsets/Boto3/boto3.tgz is 244.55 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To github.com:jamesoff/Dash-User-Contributions.git
 ! [remote rejected]   boto3-2023-03-22 -> boto3-2023-03-22 (pre-receive hook declined)
error: failed to push some refs to 'github.com:jamesoff/Dash-User-Contributions.git'
git push -u origin boto3-2023-03-22  9.13s user 1.54s system 12% cpu 1:23.71 total

Dash-User-Contributions/docsets/Boto3 1 % ll
.rw-r--r--@ 256M sewardjm 22 Mar 11:38  boto3.tgz
[snip]

Dash-User-Contributions/docsets/Boto3 % rm -f /tmp/boto3.tgz
Dash-User-Contributions/docsets/Boto3 % cd "/Users/sewardjm/Library/Application Support/doc2dash/DocSets" && \
                tar --exclude='.DS_Store' --zstd -cf /tmp/boto3.tar.zstd boto3.docset

Dash-User-Contributions/docsets/Boto3 % ll /tmp/boto3.tar.zstd
.rw-r--r--@ 49M sewardjm 22 Mar 11:45  /tmp/boto3.tar.zstd
```

**Comment by Kapeli** [comment]
Supporting other compression formats is a bit tricky, as Dash keeps the docsets archived and only unarchives the files that are needed on-the-fly.

Please upload the docset archive to Dropbox or something similar and open a pull request and provide a link to the docset.

**Comment by jamesoff** [comment]
Thought that might be the case, thanks. I've uploaded it to an S3 bucket and shared a URL in the PR which is valid for ~12h from now (figured that should be enough if you're around at the moment ;). Let me know if it expires before you can use it and I'll sort something out, but it was easiest to let work host it!

**Comment by jamesoff** [comment]
Closing this as we seem to have a reasonable solution via S3 now.
