### ISSUE TITLE
Possibility of cross-page table of contents

### ISSUE THREAD

**Issue by Mick235711** [Kapeli/Dash-User-Contributions#4422]
Currently, the table of contents feature only supports navigation within a single HTML page's different sections.
However, most docsets actually arrange the sections on different pages (such as most readthedocs docsets). A quick example would be something like [this](https://questionary.readthedocs.io/en/stable/pages/types.html):
![CleanShot 2023-08-09 at 15 26 08@2x](https://github.com/Kapeli/Dash-User-Contributions/assets/22275534/fbaf7025-db57-4cce-98b0-14404817dd06)
As you can see, each top-level entry on the left pane is actually pointing to its own page, and secondary entries are pointing to sections within a page.

Currently, in Dash, the only way to implement this would be to manually concatenate all pages into one huge HTML page and then add the anchors. However, since we lack multi-level TOC support now, we then cannot use the left pane to navigate sections within original pages. Also, this might screw up the styles if different pages are using different CSS stylesheets.

Another "solution" used by most docsets currently in Dash is to just add the pages independently to the database. However, secondary pages can only be emulated by inserting "Top Page Name - Second Page Name" or not inserted at all (such as the following screenshot of the Boost docset, notice that only the top-level libraries page are indexed within the database and you can only use the front/back buttons to navigate between pages within the library)
![CleanShot 2023-08-09 at 15 28 22@2x](https://github.com/Kapeli/Dash-User-Contributions/assets/22275534/c2abb627-5017-47c3-89f1-910b0166cb7a)
Some docsets are nice enough to put a previous/next link at the top of every page so that we do not need to go back to the contents page every time (see below); however, this is still not as convenient as just clicking the entry in the left panel (in this case, both first and secondary entries point to their own pages)
![CleanShot 2023-08-09 at 15 33 09@2x](https://github.com/Kapeli/Dash-User-Contributions/assets/22275534/25e28fc4-2e3a-4091-b7d3-9886787f3f06)
Is there any plan or timeline for multi-page TOCs or multi-level TOCs to be supported?

**Comment by Kapeli** [comment]
Hierarchical docset indexes are not currently on my todo list, sorry.
