### ISSUE TITLE
Update Requests library docset? Latest is 2.7.0

### ISSUE THREAD

**Issue by jjarava** [Kapeli/Dash-User-Contributions#448]
The Docset at the repo is for v1.0.0; I've found a feed for Dash docsets at http://python-dashapp.tk/ that provides v.2.3.0 but I'd appreciate having the latest docs available. 

Thanks!!!

**Comment by Kapeli** [comment]
@mcowger Can you update when you get a chance?

**Comment by mcowger** [comment]
I dont actually use Dash anymore :(
