### ISSUE TITLE
PHP docset outdated

### ISSUE THREAD

**Issue by cweiske** [Kapeli/Dash-User-Contributions#4565]
The current PHP manual date is 2020-01-05, which is 3 years old.
PHP 8 happened since then, and many classes and functions are not available in the dash docset.

Please update this docset.
(I'm using Zeal on Linux, and that tells me no update is available for the PHP docset).

**Comment by Kapeli** [comment]
The PHP docset is updated every month. The latest one is from 2023-08-15. Please contact Zeal's developer regarding this.
