### ISSUE TITLE
docsetcontrib script

### ISSUE THREAD

**Issue by lshprung** [Kapeli/Dash-User-Contributions#4589]
I see that pull request verification involves a verification script (available [here](https://kapeli.com/feeds/zzz/docsetcontrib.tgz)), but it appears this script is a binary file compiled for MacOS. Any chance the source of this script can be made available (or if it is available somewhere, please point out where)? I would like to be able to verify my docset contributions before submitting a pull request.

**Comment by Kapeli** [comment]
The source is not available, sorry.

You can verify your changes before submitting a pull request using:

```
wget http://kapeli.com/feeds/zzz/docsetcontrib.tgz && tar -xzf docsetcontrib.tgz && ./docsetcontrib --verify
```

**Comment by lshprung** [comment]
I am on a Linux machine, and it appears the binary only runs on MacOS (correct me if I'm wrong). Any way to verify on non-MacOS systems?
