### ISSUE TITLE
Vulkan docset doesn't let you search for vkCmdPushDescriptorSetWithTemplateKHR

### ISSUE THREAD

**Issue by mikejsavage** [Kapeli/Dash-User-Contributions#4722]
Hi, cc @antiagainst 

`vkCmdPushDescriptorSetWithTemplateKHR` is present in the docset (search for `vkCmdPushDescriptorSetKHR` and scroll down a bit) but you can't search for it directly.

I looked at the source ([chap14.html](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap14.html#vkCmdPushDescriptorSetWithTemplateKHR)) and couldn't see any obvious reason why it doesn't get picked up and I haven't noticed anything else missing in the docset.

**Comment by antiagainst** [comment]
Ha, thanks for reporting the issue. I think it's due to the regex I used to match commands--it's too restrictive there. I've fixed that. From next release you should be able to search the symbol directly.

I'll close this later when pushing an update to the Vulkan docset.
