### ISSUE TITLE
glibc documentation is out of date

### ISSUE THREAD

**Issue by lshprung** [Kapeli/Dash-User-Contributions#4778]
glibc docset is at version 2.25, whereas the latest upstream version is 2.38. I have built [my own generation script](https://github.com/lshprung/gnu-libc-dash-docset) for this docset, as I was unsatisfied with the current one's level of indexing. I can take up maintaining this docset using my generation script, however I would like to see the name changed from "glibc" to "GNU C Library". I recognize that all this is rather opinionated, so before making any pull requests I wanted to put this out there. Please let me know if anyone has any input.

**Comment by Kapeli** [comment]
Changing the name is fine, but please change it within `docset.json`. The folder name should remain `glibc`. The folder name is not displayed to users at all, but Dash uses it as a unique identifier and it should remain the same so that users get the docset update.
