### ISSUE TITLE
How can I use icon.png to create icon for docset (e.g. Eigen)

### ISSUE THREAD

**Issue by oracleyue** [Kapeli/Dash-User-Contributions#487]
For example, I created docset for Eigen by following the author's guideline. However, I don't know where to copy the icon.png icon@2x.png (maybe docset.json) in this ./Eigen/, as result the docset doesn't have icon, shown as
![screen shot 2015-06-09 at 12 26 09](https://cloud.githubusercontent.com/assets/5046605/8055861/08b6e608-0ea3-11e5-84d6-56cb16f34692.png)
Thanks a lot!

**Comment by Kapeli** [comment]
For the purpose of this repo, you're supposed to copy it right next to `docset.json`. After that, the icon will show in Dash when users install the docset from Preferences > Downloads > User Contributed.

If you just want to add an icon to the docset itself, see https://kapeli.com/docsets#addingicon.

**Comment by oracleyue** [comment]
Oh, I got it. Actually I don't need to compile it by myself and copy the Eigen.docset to the ~/Library/Application ..... /docset/. I can directly installed them from the Dash preference. Thanks!
