### ISSUE TITLE
Function signatures misalignment

### ISSUE THREAD

**Issue by hologerry** [Kapeli/Dash-User-Contributions#4895]
The parameters and the types are misaligned to the function name, as well as the code formatted text on recent latest version Dash app.
The documents are PyTorch ones (PyTorch, torchvision, torchtext, torchaudio).
@Kapeli Could you please check on the Dash side?
<img width="930" alt="image" src="https://github.com/Kapeli/Dash-User-Contributions/assets/11660168/2cf49e11-d09d-46c0-bdf9-1f78909971a6">

**Comment by Kapeli** [comment]
This happens in Safari as well, so it's more of a CSS/styling issue I think.

**Comment by hologerry** [comment]
This issue is solved in pytorch https://github.com/pytorch/pytorch_sphinx_theme/pull/196
