### ISSUE TITLE
Remove polyfill service in OpenCV.docset and others

### ISSUE THREAD

**Issue by zhouzq-thu** [Kapeli/Dash-User-Contributions#5022]
In [OpenCV.docset](https://github.com/Kapeli/feeds/blob/master/OpenCV.xml) 4.10, the html contains
```
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
```

However, polyfill contains malicious content see
-  https://github.com/polyfillpolyfill/polyfill-service
- [Formerly legitimate Polyfill.io domain abused to serve malicious code](https://www.csoonline.com/article/2505496/formerly-legitimate-polyfill-io-domain-abused-to-serve-malicious-code.html)

**Comment by Kapeli** [comment]
Thanks for letting me know about this. I've removed it and will also check other docsets for it.
