### ISSUE TITLE
Is there any Typescript Docset out there?

### ISSUE THREAD

**Issue by bkristensen** [Kapeli/Dash-User-Contributions#533]
Any one found a TypeScript docset for Dash?

**Comment by joaocc** [comment]
That would be great!

**Comment by 0x001D** [comment]
+1

**Comment by Kapeli** [comment]
A TypeScript docset made by me will be added to Dash in the next update.

**Comment by jordandobson** [comment]
Did this ever happen? I can't seem to find it when I search for a download.

**Comment by Kapeli** [comment]
@jordandobson It has. TypeScript is available in Dash since v3.1.3.

**Comment by wenroo** [comment]
Great!!!

**Comment by qiluo** [comment]
@Kapeli, I didn't find it in my Dash 2, do I have to upgrade Dash major version to see it? Thanks
