### ISSUE TITLE
Docset larger than 100 MB.

### ISSUE THREAD

**Issue by alexwidener** [Kapeli/Dash-User-Contributions#565]
How would you like to transfer it?
PyMel: http://help.autodesk.com/cloudhelp/2016/ENU/Maya-Tech-Docs/PyMel/

**Comment by Kapeli** [comment]
Upload it anywhere you can (e.g. Dropbox) and I'll take it from there.

**Comment by alexwidener** [comment]
My fault, it was 3 AM when I was working on this. I skipped over the 'archive' part and the docset itself was over 100 MB. Closing issue and submitting pull request.
