### ISSUE TITLE
Possible to use docs sets with Zeal

### ISSUE THREAD

**Issue by BigBlockStudios** [Kapeli/Dash-User-Contributions#586]
I'm trying to add the modx docset to zeal. 

how do I do this?

**Comment by Kapeli** [comment]
Please open an issue on Zeal's repo for help with Zeal. I'm only able to provide support for Dash.

This issue might be related to your request: https://github.com/zealdocs/zeal/issues/170.

**Comment by BigBlockStudios** [comment]
I will - though, it seems to be looking for a "Feed URL" I assumed it was just downloading a tarball or something - right in the Zeal config it says doc repos are provided by Dash, so I assumed to start here first.

**Comment by BigBlockStudios** [comment]
Actually, your link there was just the ticket about halfway down it describes how to "find" the feeds in this case it's:

http://newyork.kapeli.com/feeds/zzz/user_contributed/build/MODX/MODX.tgz

However I get an invalid docset after it finishes downloading :(
