### ISSUE TITLE
Update Scrapy library docset? Latest is 1.0.

### ISSUE THREAD

**Issue by matiskay** [Kapeli/Dash-User-Contributions#599]
The version that the repository provides is 0.22 and the latest version is 1.0.

* Docset: https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Scrapy.

* Scrapy Documentation: http://doc.scrapy.org/en/1.0/

**Comment by Kapeli** [comment]
@iamaziz Can you update when you get a chance?

**Comment by iamaziz** [comment]
Here it is #630 :-)

**Comment by Kapeli** [comment]
:purple_heart:
