### ISSUE TITLE
Manuals for various scala libraries

### ISSUE THREAD

**Issue by cvogt** [Kapeli/Dash-User-Contributions#614]
In Scala land, the api docs are often pretty sparse and separate manuals are published. I wrote a generator that downloads a hand full of them, turns them into docsets using dashing and publishes them as feeds here http://cvogt.org/releases/docsets/ .

Feel free to integrate into the main docset repository.

my generator tool is here https://github.com/cvogt/scala-dash

**Comment by Kapeli** [comment]
To contribute a docset please follow the instructions: https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset. I can't integrate docsets myself as I'd also have to make sure they're updated and for user-contributed docsets it would take too much time.
