### ISSUE TITLE
Generation fails on OSX

### ISSUE THREAD

**Issue by fbcom** [Kapeli/Dash-User-Contributions#622]
After installing doc2dash and cloning the repo I get:

```bash
$ ./generate.sh 
Fetching the Jinja2 documentation from http://jinja.pocoo.org/docs...
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

I am using: OSX 10.9.5, bash 3.2.53(1), inside venv using virtual environment wrapper.

Best regards

**Comment by Kapeli** [comment]
This repo is for user contributions, not support regarding docset generation. Please contact the maintainer of the docset for help with generating.
