### ISSUE TITLE
Request: Keras 

### ISSUE THREAD

**Issue by speedcell4** [Kapeli/Dash-User-Contributions#637]
http://keras.io/examples/

thx~

**Comment by danbob123** [comment]
+1

**Comment by iamaziz** [comment]
here it is #781

**Comment by Alok** [comment]
Could this be updated for the latest version of keras?

**Comment by iamaziz** [comment]
For some reason, it's not allowing me download the html files as usual. It we could get the files, the update should not be an issue.
