### ISSUE TITLE
Request: Phoenix

### ISSUE THREAD

**Issue by poteto** [Kapeli/Dash-User-Contributions#641]
http://hexdocs.pm/phoenix/Phoenix.html

Thank you!

**Comment by danmcclain** [comment]
+1

**Comment by linstula** [comment]
:+1:

**Comment by michaeldupuisjr** [comment]
+1

**Comment by Kapeli** [comment]
You can install docs for anything on hexdocs.pm from Preferences > Downloads > Hex Docsets since Dash 3.1.1. Are those docsets not suitable for your needs?

**Comment by poteto** [comment]
Sorry, you're right! I didn't realize the option was there.

**Comment by Kapeli** [comment]
No problem. Thanks to your issue I found out that the hexdocs.pm team changed the doc style and my generator wasn't working properly anymore. I've updated it and everything should be ok now.

:+1:

**Comment by poteto** [comment]
Thanks for responding so quickly, and for an awesome piece of software!
