### ISSUE TITLE
Update React Native to 0.11.0 stable

### ISSUE THREAD

**Issue by pirafrank** [Kapeli/Dash-User-Contributions#642]
Please update react native docset 0.11.0 from rc to stable.

**Comment by Kapeli** [comment]
@epitaphmike Can you look into this when you get a chance?

**Comment by epitaphmike** [comment]
No problem. The docs are actually 0.11.0 stable, I will update the repo to reflect the appropriate title and version.

**Comment by pirafrank** [comment]
I thought it was different reading at the official changelog. 
Thank you, man!

**Comment by epitaphmike** [comment]
Awaiting pull request. Should be updated momentarily.

**Comment by Kapeli** [comment]
Closed: https://github.com/Kapeli/Dash-User-Contributions/pull/644. Thank you @epitaphmike!
