### ISSUE TITLE
Datomic in Clojure would be great

### ISSUE THREAD

**Issue by sdegutis** [Kapeli/Dash-User-Contributions#671]
http://docs.datomic.com/clojure/

Forgot how to do this process though. Any hints?

**Comment by bilekt3** [comment]
I have same thoughts about Datomic - but  generally I will prefer something like my attachment. 

Despite fact that Datomic has relative strict license I do not know if public redistribution will be possible.

How many will be interested? I will start process to ask Congnitect for permission to publish documentation and make my private docs public and Dash fully compatible.

![screen shot 2015-11-02 at 09 15 48](https://cloud.githubusercontent.com/assets/381740/10876993/52ff0cb0-8142-11e5-978d-4fa93c3c3675.png)

**Comment by aviflax** [comment]
+1
