### ISSUE TITLE
Haskell docset is missing the GHC API modules

### ISSUE THREAD

**Issue by erantapaa** [Kapeli/Dash-User-Contributions#686]
The Haskell docsets are missing the docs for the `ghc` module which comes with the Haskell Platform but is "hidden" by default.

For the latest version of the Haskell Platform, if you run:

    ghc-pkg expose ghc-7.10.2

before running your docset generation command I believe you will include the `ghc` module.

See https://gist.github.com/erantapaa/987d44dca7ee2e919dae for more info on the matter.

For reference, the docs for the `ghc` module look like this: http://haddock.stackage.org/lts-3.2/ghc-7.10.2/index.html

**Comment by Kapeli** [comment]
Are GHC docs needed by most users? No one else reported this issue yet so I'm not sure if I should include them.

**Comment by erantapaa** [comment]
The GHC API is used extensively by programs which need to parse / analyze Haskell programs like __haddock__ - the documentation generator, __ghc-mod__ - the helper program for vi / emacs / etc., __HaRe__ - the Haskell refactoring tool, __haste__ - the Haskell to JS compiler, and others. All told, about 100 packages directly used the GHC API.

It's your call. Everyone who downloads Haskell has those libraries and can use the GHC API in their programs, so just for completeness I would include them either with the standard Haskell docset or as separate docset.

**Comment by PierreR** [comment]
Sorry to hijacking the issue but would it be possible to have docsets for **all** packages present in stackage ?

**Comment by Kapeli** [comment]
@PierreR Support for Haskell packages is something I'm working on right now, but I'll be using Hackage and not stackage. It should come in the next Dash update.

![screen shot 2015-11-09 at 00 18 45](https://cloud.githubusercontent.com/assets/1445635/11023091/b156ac3e-8677-11e5-8158-5f362b7f2b25.png)

**Comment by PierreR** [comment]
@Kapeli So I will be able to choose any package from Hackage ? That would be wonderful !

**Comment by Kapeli** [comment]
Yep.
