### ISSUE TITLE
Remove MatPlotLib as it is now provided by kapeli

### ISSUE THREAD

**Issue by 153957** [Kapeli/Dash-User-Contributions#693]
This docset can be removed, in favor of the officially included one:
https://github.com/Kapeli/Dash-User-Contributions/tree/6ca97fba3b98845b92274d0d99ebac2e3e3b4bd3/docsets/matplotlib

**Comment by Kapeli** [comment]
@iamaziz Is it ok if I remove your MatPlotLib docset or would you like to keep supporting it?

**Comment by Kapeli** [comment]
Also, the Pandas docset should probably be removed as well.

**Comment by iamaziz** [comment]
Which one is the official, are there other docsest for matplotlib and pandas ? I am following here :/

**Comment by Kapeli** [comment]
Dash 3.1.3 which was just released contains docsets for MatPlotLib and Pandas in Preferences > Downloads > All Docsets.

**Comment by iamaziz** [comment]
Oh, great! just updated, Dash is going more pythonic now :+1:  sure thing it's better to remove them since there is official releases now. Doesn't make sense to keep both.

**Comment by iamaziz** [comment]
I would vote for renaming the MatPlotLib to matplotlib.

**Comment by 153957** [comment]
+1 on the rename, use either matplotlib or Matplotlib (both are used in the documentation).

**Comment by Kapeli** [comment]
I'll rename it to Matplotlib.
