### ISSUE TITLE
Vue.js docset is outdated

### ISSUE THREAD

**Issue by Kapeli** [Kapeli/Dash-User-Contributions#706]
@chase can you update it when you can?

**Comment by chase** [comment]
@Kapeli Afraid I don't use Dash any longer and I don't have time to maintain the docset.

The docset generator source code from 2 years ago is located here: https://github.com/chase/vue-dash-generator

**Comment by Kapeli** [comment]
The next version of Dash (v3.2.0) will include an "official" Vue.js docset maintained by me. When that is released, the current user contributed Vue.js docset will be removed.

**Comment by wa3l** [comment]
@Kapeli any updates on this? The [website](https://kapeli.com/dash) says there is a Vue.js docset but the app doesn't actually have it.

**Comment by Kapeli** [comment]
A Vue.js docset is available in Dash since v3.2.0. If you're not seeing it in Preferences > Downloads, it means you're using an older version of Dash.

**Comment by wa3l** [comment]
@Kapeli emailed you about a license issue after updating to the latest version.
