### ISSUE TITLE
React Native 0.15.0

### ISSUE THREAD

**Issue by janmonschke** [Kapeli/Dash-User-Contributions#714]
Currently there's only 0.13.0 in the repository

**Comment by Kapeli** [comment]
@epitaphmike Can you update this when you can?

**Comment by epitaphmike** [comment]
Will update within the next day or two.

**Comment by epitaphmike** [comment]
Pull Request in. Sorry for the delay. Its been a busy few weeks.

**Comment by janmonschke** [comment]
@epitaphmike Thx a lot :)
