### ISSUE TITLE
Responsive text justification missing

### ISSUE THREAD

**Issue by Tkizzy** [Kapeli/Dash-User-Contributions#739]
Would be great if this docset was responsive to different view sizes.

**Comment by Kapeli** [comment]
Which docset?

**Comment by Tkizzy** [comment]
Apologies. The Pythonista set. I have word from the uploader that he's working on it.

**Comment by leesavide** [comment]
The Pythonista & Editorial docsets have some slight issues concerning being displayed to the device width properly when being viewed on mobile devices. The quickest and easiest fix is to simply view the these docsets in landscape mode.

If an alternative is preferred, I'll see if their might be a way to tease the static CSS & HTML files to play nicely with smaller screens. :)

If that doesn't work, I'll attempt to work around it by making a separate Sphinx project out of the sources.

**Comment by leesavide** [comment]
The other issue that could be causing the text justification could be the font size on the iOS app. If you reduce the font size, it'll make the page fit the screen, as well, without landscape.
