### ISSUE TITLE
Forced upgrade - why are you ignoring my support requests?

### ISSUE THREAD

**Issue by tkambler** [Kapeli/Dash-User-Contributions#742]
@Kapeli / Bogdan - I have contacted you at support@kapeli.com *five* times over the past two weeks to no avail. Why are you ignoring my repeated requests for support?

I was a happy, satisfied, *paid* user of Dash v2 until recently. OS X complained that Dash had become corrupted and that I must re-download it. I did so, and was *forced* to upgrade to v3. As a result, I am now continually harassed to pay you another $20. How can this be resolved?

**Comment by Kapeli** [comment]
This is not the place for support requests.
