### ISSUE TITLE
"Official" Jekyll docset

### ISSUE THREAD

**Issue by Kapeli** [Kapeli/Dash-User-Contributions#743]
Hi @alexlafroscia. This is just a heads-up that a Jekyll docset made by me will be released in the next Dash update.

Please let me know what you would like to happen with your Jekyll docset in the user contributed section? Should I remove it or will you continue to support it alongside my own docset? Either way is fine with me.

If you want to check out my own docset, you can grab it from http://kapeli.com/feeds/Jekyll.tgz. Let me know if you have any comments or notice anything wrong.

**Comment by alexlafroscia** [comment]
Oh no, definitely just remove it. Thanks for the heads-up!

**Comment by Kapeli** [comment]
:+1:
