### ISSUE TITLE
History Navigation: Backspace (Previous Page)

### ISSUE THREAD

**Issue by ear** [Kapeli/Dash-User-Contributions#744]
Would it be possible to add `backspace` as a way to go back 1 page in the history, like the browsers do?

Thank you!

**Comment by Kapeli** [comment]
I will add this if more users ask.

Please note that this is not the place for feature requests. Please contact me here in the future: https://kapeli.com/contact.

**Comment by ear** [comment]
Sorry! Thank you for considering it. Muscle memory is hard to combat :)
