### ISSUE TITLE
Keyword for Eigen

### ISSUE THREAD

**Issue by ppwwyyxx** [Kapeli/Dash-User-Contributions#754]
According to https://github.com/zealdocs/zeal/issues/383, the default search keyword for docset is ``DocSetPlatformFamily``.
With the eigen docset, this keyword is set to ``doxygen``, which doesn't make a lot of sense.

**Comment by Kapeli** [comment]
@elrnv Can you set the keyword to something like `eigen`?

**Comment by elrnv** [comment]
Can do. It must have been changed during the latex pictures were updated, so I'm gonna need some time to figure out how to get a build with latex pictures to show properly ( would appreciate a hint from @oracleyue :) ). Also, I might as well update the docs to the latest version.
