### ISSUE TITLE
Can't upload new version of Pythonista docsets

### ISSUE THREAD

**Issue by leesavide** [Kapeli/Dash-User-Contributions#771]
I unfortunately can't push the current docsets without being able to use Git LFS, as the docsets is now over the 100 MB cap. (´●△● `) I'm also unable to push the files to my fork, and get the message:
```
Git LFS: (0 of 2 files) 0 B / 126.96 MB
Git LFS objects can not be uploaded to this public fork.
Docs: https://github.com/contact
error: failed to push some refs to 'https://github.com/leesavide/Dash-User-Contributions.git'
```
How can we fix this?

**Comment by Kapeli** [comment]
Make a pull request that changes the `docset.json` to add the new version and upload the docset somewhere else (e.g. Dropbox). I'll handle it from there.

Git LFS is great but I can't have it as a requirement for this repo.

**Comment by leesavide** [comment]
Perfect, I've got it uploaded from Github releases :) :+1: Thanks!
