### ISSUE TITLE
Request:  GNU C Library (glibc) / POSIX.1-2008 Library

### ISSUE THREAD

**Issue by davidwed** [Kapeli/Dash-User-Contributions#776]
I know that the Doxygen documents can be convert to docset easily on Mac OS. 
I' am using Windows/Linux. When I try to generate the docset, I can't found the alternatives for the 'docsetutil' provided by Xcode.
Would you please offer the  GNU C Library (glibc) / POSIX.1-2008 docset?

http://pubs.opengroup.org/onlinepubs/9699919799/functions/contents.html

**Comment by deadloko** [comment]
I have generated glibc documentation from official one available here: https://www.gnu.org/software/libc/manual/

I'm think it's still not ready for contribution, but you may want to check it out. https://github.com/deadloko/glibcdash

**Comment by davidwed** [comment]
Looks good. Thanks.

**Comment by davidwed** [comment]
In my opinion the docset is good enough :+1: Do you provide the docset to the Dash-User-Contributions repo ?
