### ISSUE TITLE
I want to submit a new version of theano docs

### ISSUE THREAD

**Issue by maplewizard** [Kapeli/Dash-User-Contributions#795]
I have made a new dash docs for theano. I have two questions:
1. I found theano 0.6 in this repo, but I can't find theano docsets in dash's download list. Why?
2. I have made a theano 0.7 docs, I want to know wheather I can submit it?

**Comment by Kapeli** [comment]
1. I'm able to find Theano in Preferences > Downloads > User Contributed
2. Yes, you can

**Comment by maplewizard** [comment]
@Kapeli Should I put my files into the Theano floder or I should create a new one?

**Comment by Kapeli** [comment]
You should update the current Theano docset
