### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by redwolf0302** [Kapeli/Dash-User-Contributions#818]
The webpack

**Comment by lzane** [comment]
there is webpack 3 doc already there to be downloaded.
but it is not up to date since webpack 4 has released for quite a long time.

**Comment by godbout** [comment]
gonna try to take care of that one. v5.

**Comment by godbout** [comment]
one more doc full of js that breaks everywhere. but gonna get it.

**Comment by godbout** [comment]
v4 coming too.
