### ISSUE TITLE
Adding ITK docset

### ISSUE THREAD

**Issue by get9** [Kapeli/Dash-User-Contributions#854]
I'd like to add the [Insight Toolkit](http://itk.org/) documentation to Dash. However, it's a fairly large toolkit with extensive documentation. The compressed version of the docset is 2.3 GB. I can shrink that down probably by two thirds by excluding inheritance maps and collaboration diagrams included on every class doxygen page [like this](http://www.itk.org/Doxygen/html/classitk_1_1Array__inherit__graph.png), but by my calculations it will still be very much above the 100 MB limit. Any suggestions on how to add this to Dash?

**Comment by Kapeli** [comment]
Just make a pull request containing everything except the actual docset tgz, and upload the tgz separately somewhere (anywhere) and let me know where it is and I'll set up the rest.

**Comment by phcerdan** [comment]
This would be great @get9!
