### ISSUE TITLE
Elm Docset: Redundant package name bug

### ISSUE THREAD

**Issue by chinuka** [Kapeli/Dash-User-Contributions#875]
I use this docset, thanks for maintenance.
https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Elm

I found this docset has displayed redundant package names.

Example: [Signal#merging](http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Signal#merging)
Elm official: `merge : Signal a -> Signal a -> Signal a`
Dash.app: `merge : Signal.Signal a -> Signal.Signal a -> Signal.Signal a`

<img width="982" alt="dash" src="https://cloud.githubusercontent.com/assets/17959653/14049307/ca88305a-f2f7-11e5-94eb-acc149ec09b1.png">

**Comment by Kapeli** [comment]
@splodingsocks or @pdamoc can you look into this?

**Comment by pdamoc** [comment]
This is an issue with the generator. 
I have added the issue and will look for a solution.

**Comment by Kapeli** [comment]
Thanks @pdamoc!

Closing here. No need to have this issue tracked in 2 places.
