### ISSUE TITLE
Terraform readme outdated?

### ISSUE THREAD

**Issue by iigorkarpov** [Kapeli/Dash-User-Contributions#902]
%git clone https://github.com/f440/terraform.git
Cloning into 'terraform'...
remote: Counting objects: 69540, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 69540 (delta 17), reused 7 (delta 7), pack-reused 69514
Receiving objects: 100% (69540/69540), 40.56 MiB | 1.80 MiB/s, done.
Resolving deltas: 100% (42622/42622), done.
Checking connectivity... done.
%cd terraform/website
%git checkout docsets
error: pathspec 'docsets' did not match any file(s) known to git.

**Comment by Kapeli** [comment]
@f440 Can you look into this please?

**Comment by f440** [comment]
I'm sorry for the confusion. I fixed it at #903.
