### ISSUE TITLE
Offer: PostGIS 2.2.3dev and PostGIS 2.3.0dev

### ISSUE THREAD

**Issue by frankhommers** [Kapeli/Dash-User-Contributions#916]
I haven't exactly followed your steps to create docsets, instead I forked the existing PostGIS docset generator and improved (a lot) on it. 

What do I need to do next to include these as a User Contribution?
Files are here: https://github.com/frankhommers/postgis-docset/tree/master/dist

**Comment by Kapeli** [comment]
You need to fork this repo and update the files at https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/PostGIS. Specifically, you need to update the `docset.json` to change its version and add the `PostGIS.tgz` archive inside that folder.

If you want to support multiple versions of the docset, you need to add `specific_versions` to the `docset.json`. See https://github.com/Kapeli/Dash-User-Contributions/blob/master/Sample_Docset/docset.json#L14-L25.

When you're done, submit a pull request.
