### ISSUE TITLE
Node.js docset missing some modules

### ISSUE THREAD

**Issue by CatTail** [Kapeli/Dash-User-Contributions#920]
Missing modules including

* [debugger](https://nodejs.org/dist/latest-v6.x/docs/api/debugger.html)
* [Errors](https://nodejs.org/dist/latest-v6.x/docs/api/errors.html)
* [Process](https://nodejs.org/dist/latest-v6.x/docs/api/process.html)

**Comment by Kapeli** [comment]
I'll look into `debugger` not being indexed.

`Process` is not a module as far as I can tell. The NodeJS index marks it as a [`global`](https://nodejs.org/dist/latest-v6.x/docs/api/process.json). If you search for `process` in Dash you'll find it.

Same thing for `Errors`, it's not a module as far as I can tell.

**Comment by CatTail** [comment]
Thanks for your response :), Further issue will directly mail to contact.
