### ISSUE TITLE
How can I contributed way-toooo-large docsets?

### ISSUE THREAD

**Issue by Naville** [Kapeli/Dash-User-Contributions#921]
Or, any idea on reducing their size?

I'm talking about https://github.com/Naville/LLVM_Docsets

**Comment by Naville** [comment]
fyi, I used this doxygen cfg to generate the docset from Clang SVN Trunk

https://gist.github.com/Naville/7169ffdcc5ad132898d46f83cc70b688

**Comment by Kapeli** [comment]
There's no way to reduce the size as far as I know.

To contribute them you should make a pull request adding everything that's needed (e.g. `docset.json`), but don't add the docset archive. Instead of the archive, give me a link to where I can download it.
