### ISSUE TITLE
Transfer Others User Contributed Docsets to iOS

### ISSUE THREAD

**Issue by epitaphmike** [Kapeli/Dash-User-Contributions#953]
I just bought a new iPad and I wanted to download a few docsets. I have no problem downloading base docsets or transferring docsets I have created, but I can't seem to be able to transfer other user contributed docsets. I am guessing because you remove the .docset files from your github repo.

Any suggestions?

Thanks.

**Comment by Kapeli** [comment]
Support for user contributed docsets on iOS is planned. In the meantime, the workaround is to install them using Dash for OS X and then transfer them to iOS using iTunes.
