### ISSUE TITLE
Cannot read DocSet when import the DocSet via iTunes into my iPhone

### ISSUE THREAD

**Issue by MarcSteven** [Kapeli/Dash-User-Contributions#994]
Good nite,I have a doubt.
I imported downloaded DocSet into my iPhone,and then  I enter into the menu of transfer DocSets and then I found the DocSet and then click the icon,it started to transfer ,finally it got successful.
But the issue appeared here.I opened the DocSet ,it crashed right now....
Eg:I imported the iOS offline DocSet ,the size of DocSet is 2.57GB.........the mode of transferring  docket is good to use........Any errors here,pls point out ....Hope the feeling of using the app is better than before....Good tool to develop    better app.......

**Comment by Kapeli** [comment]
This is not the place to report issues for the iOS app. Please [contact me](https://kapeli.com/contact).
